#!/bin/bash
SCRIPT_VERSION=2.0.8

#/////////////////////////////////////////////////////
# CHANGELOG
#/////////////////////////////////////////////////////

SCRIPT_CHANGELOG="
2.0.8
  + User Tweaks added

2.0.6
  + New Tweaks Mechanism
  + Big Refactoring
"

#/////////////////////////////////////////////////////
# SCRIPT VARIABLES
#/////////////////////////////////////////////////////

SCRIPT_ID="ecos"
SCRIPT_DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
SCRIPT_FILE="$SCRIPT_DIR/$(basename "$0")"
SCRIPT_TUI_FILE="$SCRIPT_DIR/$SCRIPT_ID.tui"
SCRIPT_TUI_WIDTH=68
SCRIPT_TUI_HEIGHT=24

#/////////////////////////////////////////////////////
# ECOS VARIABLES
#/////////////////////////////////////////////////////

# URLS
ECOS_REPO_URL="https://github.com/murkl/ecos.git"
ECOS_DOTS_DEFAULT_URL="https://github.com/murkl/dotfiles-gnome.git"
ECOS_RAW_URL="https://raw.githubusercontent.com/murkl/ecos/main"
ECOS_TWEAKS_URL="$ECOS_RAW_URL/tweaks"
ECOS_CORE_URL="$ECOS_RAW_URL/ecos"
ECOS_ARCH_ISO_DEFAULT_URL="https://www.archlinux.de/download/iso/2021.11.01/archlinux-2021.11.01-x86_64.iso"

# ECOS
ECOS_HOME="$HOME/.ecos"
ECOS_WORKING_DIR="$ECOS_HOME/.cache"
ECOS_BIN_DIR="$ECOS_HOME/bin"
ECOS_CORE="$ECOS_BIN_DIR/$SCRIPT_ID"
ECOS_INIT="$ECOS_HOME/init"
ECOS_LOCAL_DOTFILES="$ECOS_WORKING_DIR/dotfiles"
ECOS_INITIALIZED="$ECOS_WORKING_DIR/initialized"
ECOS_CACHE_REPO_ECOS="$ECOS_WORKING_DIR/repo"
ECOS_CACHE_TWEAKS="$ECOS_WORKING_DIR/tweaks"
ECOS_USER_TWEAKS="$ECOS_HOME/tweaks"
ECOS_SHOW_CHANGELOG="$ECOS_WORKING_DIR/show_changelog"
ECOS_ARCH_ISO_FILE="$ECOS_WORKING_DIR/archlinux-x86_64.iso"
ECOS_DESKTOP_FILE="$HOME/.local/share/applications/$SCRIPT_ID.desktop"

#/////////////////////////////////////////////////////
# CORE VARIABLES
#/////////////////////////////////////////////////////

CORE_CONFIG_FILE="$SCRIPT_DIR/$SCRIPT_ID.conf"
CORE_LOG_FILE="$SCRIPT_DIR/$SCRIPT_ID.log"

# DEFAULT CORE CONFIG VALUES
USERNAME=''
HOSTNAME=''
WORKSTATION=''
SWAP_SIZE='0'
DISK=''
BOOT_PARTITION=''
ROOT_PARTITION=''
UCODE=''
LOCALE_LANG=''
LOCALE_GEN=('')
TIMEZONE=''
VCONSOLE_KEYMAP=''
X11_KEYBOARD_LAYOUT=''
X11_KEYBOARD_VARIANT=''
CUSTOM_PACKAGES=''

#/////////////////////////////////////////////////////
# CORE LANGUAGES
#/////////////////////////////////////////////////////

set_lang_en_US() {
    TIMEZONE='Europe/Berlin'
    LOCALE_LANG='en_US.UTF-8'
    LOCALE_GEN=('en_US.UTF-8 UTF-8')
    VCONSOLE_KEYMAP='en-latin1-nodeadkeys'
    X11_KEYBOARD_LAYOUT='en'
    X11_KEYBOARD_VARIANT='nodeadkeys'
}

set_lang_de_DE() {
    TIMEZONE='Europe/Berlin'
    LOCALE_LANG='de_DE.UTF-8'
    LOCALE_GEN=('de_DE.UTF-8 UTF-8' 'de_DE ISO-8859-1' 'de_DE@euro ISO-8859-15' 'en_US.UTF-8 UTF-8')
    VCONSOLE_KEYMAP='de-latin1-nodeadkeys'
    X11_KEYBOARD_LAYOUT='de'
    X11_KEYBOARD_VARIANT='nodeadkeys'
}

#/////////////////////////////////////////////////////
# MAIN
#/////////////////////////////////////////////////////

main() {

    #----------------------------------------
    # CHROOT MODE
    #----------------------------------------
    if [ "$1" = "--chroot" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
        core_install_chroot "$2" "$3"
        exit $?
    fi

    # ---------------------------------------
    # INIT
    # ---------------------------------------
    if [ "$1" = "--init" ]; then
        if [ ! -f "$ECOS_INITIALIZED" ]; then
            tui_menu_init
        else
            exit
        fi
    fi

    # ---------------------------------------
    # EXECUTE TWEAK
    # ---------------------------------------
    if [ "$1" = "--tweak" ]; then
        ecos_exec_tweak "$2" "$3"
        exit
    fi

    # ---------------------------------------
    # UPDATE CORE
    # ---------------------------------------
    if [ "$1" = "--update-core" ]; then
        ecos_update_core
        exit
    fi

    # ---------------------------------------
    # UPDATE ECOS
    # ---------------------------------------
    if [ "$1" = "--update-system" ]; then
        ecos_update_system
        exit
    fi

    # ---------------------------------------
    # ECOS SCRIPT_CHANGELOG
    # ---------------------------------------
    if [ "$1" = "--changelog" ]; then
        if [ -f "$ECOS_SHOW_CHANGELOG" ]; then
            tui_init 0 ""
            whiptail --title "Changelog" --scrolltext --msgbox "$(cat "$SCRIPT_TUI_FILE")\n\n$SCRIPT_CHANGELOG" $SCRIPT_TUI_HEIGHT $SCRIPT_TUI_WIDTH 3>&1 1>&2 2>&3
            rm -f "$ECOS_SHOW_CHANGELOG"
        fi
        exit
    fi

    # ---------------------------------------
    # CORE
    # ---------------------------------------
    if [ "$1" = "--core" ]; then
        tui_menu_core_install
        exit
    fi

    #----------------------------------------
    # CORE TUI | MANAGER TUI
    #----------------------------------------
    if [ "$1" = "" ]; then
        # Check if started from live iso
        if [ "$(cat /proc/sys/kernel/hostname)" = "archiso" ]; then
            tui_menu_core_install
        else
            if [ ! -f "$ECOS_INITIALIZED" ]; then
                tui_menu_welcome
            else
                tui_menu_manager
            fi
        fi
    fi
}

#/////////////////////////////////////////////////////
# TUI MENUS
#/////////////////////////////////////////////////////

tui_menu_core_install() {

    #----------------------------------------
    # Show TUI menu
    #----------------------------------------
    tui_init 24 "CORE INSTALLER"
    if ! menu_input=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3 "1" "Install ECOS Core" "2" "    Recovery" "3" "      Logs" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    #----------------------------------------
    # Install core
    #----------------------------------------
    if [ "$menu_input" = "1" ]; then
        check_internet
        core_tui_install
        exit $?
    fi

    #----------------------------------------
    # Recovery
    #----------------------------------------
    if [ "$menu_input" = "2" ]; then
        tui_open_recovery
        exit
    fi

    #----------------------------------------
    # Logs
    #----------------------------------------
    if [ "$menu_input" = "3" ]; then
        core_tui_show_logs
        tui_menu_core_install
        exit
    fi
}

tui_menu_init() {

    #----------------------------------------
    # Show TUI menu
    #----------------------------------------
    tui_init 24 "ECOS INSTALLER"
    if ! menu_input=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3 "1" "   Install ECOS" "2" "  Change Password" "3" "Manual Installation" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    #----------------------------------------
    # Install ECOS
    #----------------------------------------
    if [ "$menu_input" = "1" ]; then
        ecos_tui_install_ecos
        exit 0
    fi

    #----------------------------------------
    # Change Password
    #----------------------------------------
    if [ "$menu_input" = "2" ]; then
        passwd
        read -p "Press <ENTER> to continue..."
        tui_menu_init
        exit 0
    fi

    #----------------------------------------
    # Manual Install
    #----------------------------------------
    if [ "$menu_input" = "3" ]; then
        clear
        echo -e "\nSimply type 'ecos' to open again\n\nInstall your System manually..."
        exit 0
    fi

}

tui_menu_manager() {

    #----------------------------------------
    # Show TUI menu
    #----------------------------------------
    tui_init 28 "MANAGER"
    if ! menu_input=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 4 "1" "     Update" "2" "     Tweaks" "3" "     Reset" "4" "Create USB Stick" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    #----------------------------------------
    # Update ECOS
    #----------------------------------------
    if [ "$menu_input" = "1" ]; then
        ecos_update_core
        "$ECOS_CORE" --update-system
        exit 0
    fi

    #----------------------------------------
    # Tweaks
    #----------------------------------------
    if [ "$menu_input" = "2" ]; then
        ecos_tui_menu_tweaks
        exit 0
    fi

    #----------------------------------------
    # Init ECOS
    #----------------------------------------
    if [ "$menu_input" = "3" ]; then
        ecos_tui_install_ecos
        exit 0
    fi

    #----------------------------------------
    # Create USB Stick
    #----------------------------------------
    if [ "$menu_input" = "4" ]; then
        tui_create_usb
        exit 0
    fi
}

tui_menu_welcome() {

    #----------------------------------------
    # Show TUI menu
    #----------------------------------------
    tui_init 27 "WELCOME"
    if ! menu_input=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 2 "1" "  Install ECOS" "2" "Create USB Stick" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    #----------------------------------------
    # Install ECOS
    #----------------------------------------
    if [ "$menu_input" = "1" ]; then
        ecos_tui_install_ecos
        exit 0
    fi

    #----------------------------------------
    # Create USB Stick
    #----------------------------------------
    if [ "$menu_input" = "2" ]; then
        tui_create_usb
        exit 0
    fi
}

#/////////////////////////////////////////////////////
# CORE INSTALLATION
#/////////////////////////////////////////////////////

core_tui_install() {

    #----------------------------------------
    # Ask for reset core config
    #----------------------------------------
    if [ -f "$CORE_CONFIG_FILE" ]; then
        tui_init 15 "Continue Setup Configuration?\n"
        if ! (whiptail --yesno "$(cat "$SCRIPT_TUI_FILE")" 0 "$SCRIPT_TUI_WIDTH"); then
            core_reset_config
        fi
    fi

    #----------------------------------------
    # Check config
    #----------------------------------------
    core_tui_check_config

    #----------------------------------------
    # Encryption password
    #----------------------------------------
    tui_init 0 "Enter Encryption Password"
    if ! password_encryption=$(whiptail --passwordbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    # Confirm password
    tui_init 0 "Confirm Encryption Password"
    if ! password_input_confirm=$(whiptail --passwordbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    # Check password
    if [ "$password_encryption" != "$password_input_confirm" ]; then
        tui_init 0 "Password Mismatch! Restart the Installation..."
        whiptail --msgbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"
        exit 1
    fi

    #----------------------------------------
    # Confirm and execute install
    #----------------------------------------
    tui_init 0 "Start Installation"
    tui_add 0 "!!! ALL YOUR DATA WILL BE LOST !!!"
    tui_add 0 "Continue?"
    if (! whiptail --yesno "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"); then
        exit 0
    fi

    #----------------------------------------
    # Execute install (will execute chroot)
    #----------------------------------------
    tui_init 0 "Core Installation..."
    core_exec_install "$password_encryption" | whiptail --gauge "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 0 3>&1 1>&2 2>&3

    # Show Result
    if [ $? = 1 ]; then
        # Error message
        tui_init 0 "ERROR: INSTALLATION FAILED!"
        whiptail --msgbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"

        # Logs
        core_tui_show_logs

        exit 1
    else
        # Success message
        tui_init 0 "INSTALLATION SUCCESSFULLY FINISHED"
        whiptail --msgbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"

        # Logs
        core_tui_show_logs

        # Reboot
        tui_init 0 "Reboot now?"
        if (whiptail --yesno "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"); then
            reboot
        fi

        exit 0
    fi

}

core_exec_install() {

    local password_encryption="$1"

    #----------------------------------------
    # Source config
    #----------------------------------------
    . "$CORE_CONFIG_FILE"

    core_log "!!! INSTALLATION START !!!"

    #----------------------------------------
    # Check UEFI boot
    #----------------------------------------
    local uefi_mode=true
    if efivar -l >/dev/null; then
        core_log "UEFI detected"
    else
        core_log "BIOS detected"
        uefi_mode=false
    fi

    #----------------------------------------
    # Wipe disk
    #----------------------------------------
    core_gauge_update 4 "Wipe $DISK"
    core_exec_command_wrap sgdisk -Z "$DISK"

    #----------------------------------------
    # Partition disk
    #----------------------------------------
    core_gauge_update 8 "Partition $DISK"

    # Create new partition table
    core_exec_command_wrap sgdisk -o "$DISK"

    # Reload partition table
    core_exec_command_wrap partprobe "$DISK"

    if [ "$uefi_mode" = "true" ]; then

        # /boot partition: 512MiB
        core_exec_command_wrap sgdisk -n 0:0:+512MiB -t 0:ef00 -c 0:boot "$DISK"

        # / partition: Rest of space
        core_exec_command_wrap sgdisk -n 0:0:0 -t 0:8300 -c 1:root "$DISK"

    else

        # BIOS only: 1MiB partition is needed for GRUB (if GPT is used instead of MBR)
        core_exec_command_wrap sgdisk -n 0:0:+1MiB -t 0:ef02 "$DISK"

        # / partition: Rest of space
        core_exec_command_wrap sgdisk -n 0:0:0 -t 0:8300 -c 0:root "$DISK"
    fi

    #----------------------------------------
    # Encrypt disk
    #----------------------------------------
    core_gauge_update 10 "Encrypt $DISK"

    # Set encrypt command
    local crypt_cmd=''
    if [ "$uefi_mode" = "true" ]; then
        crypt_cmd="cryptsetup -c aes-xts-plain -s 512 luksFormat $ROOT_PARTITION"
    else
        # LUKS2 isnt implemented yet (GRUB)
        crypt_cmd="cryptsetup -c aes-xts-plain -s 512 luksFormat --type luks1 $ROOT_PARTITION"
    fi

    # Create encryption
    if ! echo -n "$password_encryption" | $crypt_cmd -d - >/dev/null; then
        core_log "e" "$crypt_cmd"
        exit 1
    else
        core_log "c" "$crypt_cmd"
    fi

    # Open encrypt
    crypt_cmd="cryptsetup open $ROOT_PARTITION cryptroot"
    if ! echo -n "$password_encryption" | $crypt_cmd -d - >/dev/null; then
        core_log "e" "$crypt_cmd"
        exit 1
    else
        core_log "c" "$crypt_cmd"
    fi

    #----------------------------------------
    # Format disk
    #----------------------------------------
    core_gauge_update 12 "Format $DISK"

    # Format /boot
    if [ "$uefi_mode" = "true" ]; then
        core_exec_command_wrap mkfs.fat -F32 "$BOOT_PARTITION"
    fi

    # Format crypted /
    core_exec_command_wrap mkfs.ext4 /dev/mapper/cryptroot

    #----------------------------------------
    # Mount disk to /mnt
    #----------------------------------------
    core_exec_command_wrap mount /dev/mapper/cryptroot /mnt

    if [ "$uefi_mode" = "true" ]; then
        core_exec_command_wrap mkdir /mnt/boot
        core_exec_command_wrap mount "$BOOT_PARTITION" /mnt/boot
    fi

    #----------------------------------------
    # Pacstrap base arch packages
    #----------------------------------------
    core_gauge_update 24 "Pacstrap Installation (may take a while)..."
    core_exec_command_wrap pacstrap /mnt base base-devel linux linux-firmware

    #----------------------------------------
    # Generate /etc/fstab
    #----------------------------------------
    core_gauge_update 52 "Generate /etc/fstab"
    local log_txt="genfstab -U /mnt >>/mnt/etc/fstab"
    if ! genfstab -U /mnt >>/mnt/etc/fstab; then
        core_log "e" "$log_txt"
        exit 1
    else
        core_log "c" "$log_txt"
    fi

    #----------------------------------------
    # Copy ecos in chroot env
    #----------------------------------------
    core_exec_command_wrap cp -f "$SCRIPT_FILE" /mnt/$SCRIPT_ID
    core_exec_command_wrap cp -f "$CORE_CONFIG_FILE" /mnt/$SCRIPT_ID.conf
    core_exec_command_wrap chmod +x /mnt/$SCRIPT_ID

    #----------------------------------------
    # Chroot into new system
    #----------------------------------------
    core_gauge_update 54 "Enter CHROOT Environement"
    log_txt="arch-chroot /mnt /$SCRIPT_ID --chroot $uefi_mode <ENCRYPTION_PASSWORD>"
    if ! arch-chroot /mnt "/$SCRIPT_ID" --chroot "$uefi_mode" "$password_encryption"; then
        core_log "e" "$log_txt"
        exit 1
    else
        core_log "c" "$log_txt"
    fi

    #----------------------------------------
    # Merge ecos logs
    #----------------------------------------
    cat "/mnt/$SCRIPT_ID.log" >>"$CORE_LOG_FILE"
    cp "/mnt/$SCRIPT_ID.error" "$SCRIPT_DIR/$SCRIPT_ID.error"
    rm -f "/mnt/$SCRIPT_ID"
    rm -f "/mnt/$SCRIPT_ID.conf"
    rm -f "/mnt/$SCRIPT_ID.log"
    rm -f "/mnt/$SCRIPT_ID.tui"

    #----------------------------------------
    # Unmount
    #----------------------------------------
    core_exec_command_wrap swapoff -a
    core_exec_command_wrap umount -R /mnt
    core_exec_command_wrap cryptsetup close cryptroot

    #----------------------------------------
    # Finished
    #----------------------------------------
    core_gauge_update 100 "Installation finished!"
    core_log "!!! INSTALLATION SUCCESSFULLY FINISHED !!!"

    exit 0
}

core_install_chroot() {

    local uefi_mode="$1"
    local password_encryption="$2"

    #----------------------------------------
    # Source config
    #----------------------------------------
    . "$CORE_CONFIG_FILE"

    #----------------------------------------
    # Essential packages
    #----------------------------------------
    local gauge_txt="Install Essential Packages (may take a while)..."

    core_gauge_update 56 "$gauge_txt"
    core_exec_command_wrap pacman -Syy

    # Boootloader, Microcode Kernel Updates for CPU & Core Tools
    core_gauge_update 58 "$gauge_txt"
    bootloader_pkgs="efibootmgr"
    if [ "$uefi_mode" = "false" ]; then
        bootloader_pkgs="grub"
    fi
    core_exec_command_wrap pacman --noconfirm --needed -S $UCODE $bootloader_pkgs dosfstools gptfdisk $CUSTOM_PACKAGES

    # Network manager
    core_gauge_update 60 "$gauge_txt"
    core_exec_command_wrap pacman --noconfirm --needed -S networkmanager

    # Default shell
    core_gauge_update 70 "$gauge_txt"
    core_exec_command_wrap pacman --noconfirm --needed -S zsh

    if [ "$WORKSTATION" = "notebook" ]; then
        # Battery safer
        core_exec_command_wrap pacman --noconfirm --needed -S tlp
    fi

    #----------------------------------------
    # Swap
    #----------------------------------------
    if [ "$SWAP_SIZE" != "0" ] && [ -n "$SWAP_SIZE" ]; then
        core_gauge_update 75 "Create Swap File"
        core_exec_command_wrap dd if=/dev/zero of=/swapfile bs=1GiB count="$SWAP_SIZE" status=progress
        core_exec_command_wrap chmod 600 /swapfile
        core_exec_command_wrap mkswap /swapfile
        core_exec_command_wrap swapon /swapfile
        echo "# Swapfile" >>/etc/fstab
        echo "/swapfile none swap defaults 0 0" >>/etc/fstab
    fi

    #----------------------------------------
    # Timezone and localization
    #----------------------------------------
    core_exec_command_wrap ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
    core_exec_command_wrap hwclock --systohc

    #----------------------------------------
    # Keymap
    #----------------------------------------
    core_log "Create /etc/vconsole.conf"
    echo "KEYMAP=$VCONSOLE_KEYMAP" >/etc/vconsole.conf
    echo "FONT=lat9w-16" >>/etc/vconsole.conf

    #----------------------------------------
    # Locale
    #----------------------------------------
    core_log "Create /etc/locale.conf"
    echo "LANG=$LOCALE_LANG" >/etc/locale.conf

    #----------------------------------------
    # Set locale.gen
    #----------------------------------------
    for locale_gen_item in "${LOCALE_GEN[@]}"; do
        sed -i "s/^#$locale_gen_item/$locale_gen_item/g" "/etc/locale.gen"
    done

    core_gauge_update 78 "Generate Locale"
    core_exec_command_wrap locale-gen

    #----------------------------------------
    # Set hostname
    #----------------------------------------
    core_log "Create /etc/hostname"
    echo "$HOSTNAME" >/etc/hostname

    #----------------------------------------
    # Set hosts
    #----------------------------------------
    core_log "Create /etc/hosts"
    {
        echo '127.0.0.1    localhost'
        echo '::1          localhost'
    } >/etc/hosts

    #----------------------------------------
    # Network
    #----------------------------------------
    core_gauge_update 80 "Configure Network"
    core_exec_command_wrap systemctl enable NetworkManager

    #----------------------------------------
    # Boot loader
    #----------------------------------------
    core_gauge_update 82 "Install Bootloader"

    if [ "$uefi_mode" = true ]; then
        #----------------------------------------
        # Bootloader: systemd-boot
        #----------------------------------------

        core_exec_command_wrap bootctl --path=/boot install

        echo 'default arch.conf' >/boot/loader/loader.conf
        echo 'timeout 0' >>/boot/loader/loader.conf
        echo 'editor  yes' >>/boot/loader/loader.conf

        echo 'title   Arch Linux' >/boot/loader/entries/arch.conf
        echo 'linux   /vmlinuz-linux' >>/boot/loader/entries/arch.conf
        [ -n "$UCODE" ] && echo "initrd  /$UCODE.img" >>/boot/loader/entries/arch.conf
        echo 'initrd  /initramfs-linux.img' >>/boot/loader/entries/arch.conf
        echo "options cryptdevice=$ROOT_PARTITION:cryptroot root=/dev/mapper/cryptroot quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_priority=3 vt.global_cursor_default=0 rw" >>/boot/loader/entries/arch.conf
    else
        #----------------------------------------
        # Bootloader: GRUB (for legacy BIOS)
        #----------------------------------------

        # Create a keyfile to prevent enter the encryption password twice
        local crypt_key="/crypto_keyfile.bin"

        core_exec_command_wrap dd bs=512 count=4 if=/dev/random of="$crypt_key" iflag=fullblock
        core_exec_command_wrap chmod 600 "$crypt_key"

        # When initramfs' permissions are set to 644 (by default), then all users will be able to dump the keyfile
        core_exec_command_wrap chmod 600 /boot/initramfs-linux*

        local crypt_cmd="cryptsetup luksAddKey $ROOT_PARTITION $crypt_key"
        if ! echo -n "$password_encryption" | $crypt_cmd -d - >/dev/null; then
            core_log "e" "$crypt_cmd"
            exit 1
        else
            core_log "c" "$crypt_cmd"
        fi

        sed -i 's^FILES=()^FILES=('$crypt_key')^g' /etc/mkinitcpio.conf
        core_exec_command_wrap mkinitcpio -p linux

        # Mdify before execute grub-install!
        echo 'GRUB_ENABLE_CRYPTODISK=y' >/etc/default/grub
        echo 'GRUB_CMDLINE_LINUX="cryptdevice='$ROOT_PARTITION':cryptroot cryptkey=rootfs:'$crypt_key'"' >>/etc/default/grub

        core_exec_command_wrap grub-install --no-floppy "$DISK"
        core_exec_command_wrap grub-mkconfig -o /boot/grub/grub.cfg
    fi

    #----------------------------------------
    # Modify HOOKS
    #----------------------------------------
    core_log "Modify /etc/mkinitcpio.conf"
    cp /etc/mkinitcpio.conf /etc/mkinitcpio.conf.bak
    sed -i "s/filesystems keyboard fsck/filesystems fsck/g" /etc/mkinitcpio.conf
    sed -i "s/udev autodetect/udev keyboard autodetect/g" /etc/mkinitcpio.conf
    sed -i "s/block filesystems/block keymap encrypt filesystems/g" /etc/mkinitcpio.conf

    #----------------------------------------
    # Rebuild initrc
    #----------------------------------------
    core_gauge_update 85 "Rebuild Initial Ramdisk"
    core_exec_command_wrap mkinitcpio -p linux

    #----------------------------------------
    # Create new user
    #----------------------------------------
    core_exec_command_wrap useradd -m -G users,wheel,video,audio,storage,disk -s /bin/zsh "$USERNAME"

    #----------------------------------------
    # Allow users in group wheel to use sudo
    #----------------------------------------
    core_log "Enable sudo in /etc/sudoers"
    sed -i '/%wheel\sALL=(ALL)\sALL/s/^#\s//g' /etc/sudoers

    #----------------------------------------
    # Auto login tty1
    #----------------------------------------
    core_gauge_update 90 "Enable Automatic Login"
    mkdir -p "/etc/systemd/system/getty@tty1.service.d/"
    {
        echo "[Service]"
        echo "ExecStart="
        echo "ExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin $USERNAME --noclear %I \$TERM"
    } >"/etc/systemd/system/getty@tty1.service.d/override.conf"
    core_exec_command_wrap systemctl enable getty@tty1

    #----------------------------------------
    # Xorg config
    #----------------------------------------

    # Create dir
    core_exec_command_wrap mkdir -p /etc/X11/xorg.conf.d/

    #----------------------------------------
    # Keyboard config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/00-keyboard.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "keyboard"'
        echo '    MatchIsKeyboard "yes"'
        echo '    Option "XkbLayout" "'$X11_KEYBOARD_LAYOUT'"'
        echo '    Option "XkbModel" "pc105"'
        echo '    Option "XkbVariant" "'$X11_KEYBOARD_VARIANT'"'
        echo 'EndSection'
    } >"/etc/X11/xorg.conf.d/00-keyboard.conf"

    #----------------------------------------
    # Mouse config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/50-mouse.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "mouse"'
        echo '    Driver "libinput"'
        echo '    MatchIsPointer "yes"'
        echo '    Option "AccelProfile" "flat"'
        echo '    Option "AccelSpeed" "0"'
        echo 'EndSection'
    } >"/etc/X11/xorg.conf.d/50-mouse.conf"

    #----------------------------------------
    # Touchpad config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/70-touchpad.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "touchpad"'
        echo '    Driver "libinput"'
        echo '    MatchIsTouchpad "on"'
        echo '    Option "ClickMethod" "clickfinger"'
        echo '    Option "Tapping" "off"'
        echo '    Option "NaturalScrolling" "true"'
        echo 'EndSection'

    } >"/etc/X11/xorg.conf.d/70-touchpad.conf"

    core_gauge_update 92 "Enable Daemons"

    #----------------------------------------
    # SSD fstrim
    #----------------------------------------
    core_exec_command_wrap systemctl enable "fstrim.timer"

    #----------------------------------------
    # Timesync service
    #----------------------------------------
    core_exec_command_wrap systemctl enable "systemd-timesyncd.service"

    #----------------------------------------
    # TODO (FAILED): Network browsing service
    #----------------------------------------
    #core_exec_command_wrap systemctl enable "avahi-daemon"

    #----------------------------------------
    # TLP (Notebook)
    #----------------------------------------
    if [ "$WORKSTATION" = "notebook" ]; then
        core_exec_command_wrap systemctl enable "tlp.service"
    fi

    #----------------------------------------
    # Pacman colors & multilib
    #----------------------------------------
    core_gauge_update 95 "Configure Pacman"
    core_log "Enable pacman multilib & colors"
    sed -i 's/^#Color/Color/g;/#\[multilib\]/,/#Include/ s/^#//g' /etc/pacman.conf
    core_exec_command_wrap pacman -Syy

    #----------------------------------------
    # ECOS Binary
    #----------------------------------------
    core_gauge_update 98 "ECOS Binary"

    # Copy ecos to local bin
    mkdir -p "/home/$USERNAME/.ecos/bin"
    cp "$SCRIPT_FILE" "/home/$USERNAME/.ecos/bin/ecos"
    chmod +x "/home/$USERNAME/.ecos/bin/ecos"

    # Create .zlogin
    local user_profile="/home/$USERNAME/.zlogin"
    echo '#!/bin/sh' >$user_profile
    echo 'export ECOS_HOME="$HOME/.ecos"' >>$user_profile
    echo 'export ECOS_CORE="$ECOS_HOME/bin/ecos"' >>$user_profile
    echo 'export PATH="$PATH:$ECOS_HOME/bin"' >>$user_profile
    echo '$ECOS_CORE --init' >>$user_profile
    chmod +x $user_profile

    #----------------------------------------
    # Deletes unnecessary files
    #----------------------------------------
    rm -f "/home/$USERNAME/.bash_logout"
    rm -f "/home/$USERNAME/.bash_profile"
    rm -f "/home/$USERNAME/.bashrc"
    rm -f "/home/$USERNAME/.zshrc"

    #----------------------------------------
    # Set user permissions
    #----------------------------------------
    chown -R "$USERNAME" "/home/$USERNAME"

    #--------------------------------------------------------
    # Change passwords
    #----------------------------------------
    core_log "Change passwords"
    #passwd root < <(echo -e "$password_encryption\n$password_encryption")
    #passwd "$USERNAME" < <(echo -e "$password_encryption\n$password_encryption")
    echo -e "$password_encryption\n$password_encryption" | (passwd)
    echo -e "$password_encryption\n$password_encryption" | (passwd "$USERNAME")

    #----------------------------------------
    # Chroot finished
    #----------------------------------------
    core_log "CHROOT successfully finished"
}

core_tui_show_logs() {
    touch "$CORE_LOG_FILE"
    tui_init 0 "$(cat "$CORE_LOG_FILE")"
    #whiptail --textbox $SCRIPT_TUI_FILE 0 $SCRIPT_TUI_WIDTH
    whiptail --msgbox "$(cat "$SCRIPT_TUI_FILE")" 0 "$SCRIPT_TUI_WIDTH"
}

core_tui_check_disk() {

    if [ "$1" = "--force" ] || [ "$DISK" = "" ] || [ "$BOOT_PARTITION" = "" ] || [ "$ROOT_PARTITION" = "" ]; then

        local disk_array=()
        while read disk_line; do
            disk_size=$(lsblk -d -n -o SIZE /dev/$disk_line)
            disk_array+=("/dev/$disk_line")
            disk_array+=(" ($disk_size)")
        done < <(lsblk -I 8,259 -d -o KNAME -n)

        tui_init 24 "Choose Disk"
        if ! DISK=$(whiptail --menu "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "${#disk_array[@]}" "${disk_array[@]}" 3>&1 1>&2 2>&3); then
            exit 0
        fi

        BOOT_PARTITION="${DISK}1"
        ROOT_PARTITION="${DISK}2"

        # NVM Express
        if [[ "$DISK" = "/dev/nvm"* ]]; then
            BOOT_PARTITION="${DISK}p1"
            ROOT_PARTITION="${DISK}p2"
        fi

    fi
}

core_tui_check_config() {

    if [ -f "$CORE_CONFIG_FILE" ]; then
        . "$CORE_CONFIG_FILE"
    fi

    #----------------------------------------
    # Check user
    #----------------------------------------
    if [ "$USERNAME" = "" ]; then
        tui_init 0 "Enter Username"
        if ! USERNAME=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3>&1 1>&2 2>&3); then
            exit 0
        fi
        if [ "$USERNAME" = "" ]; then
            tui_init 0 "Username was empty! Restart the Installation..."
            whiptail --textbox "$SCRIPT_TUI_FILE" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"
            exit 0
        fi
        core_replace_config_value "USERNAME" "$USERNAME"
    fi

    #----------------------------------------
    # Check workstation
    #----------------------------------------
    if [ "$WORKSTATION" = "" ]; then
        tui_init 20 "Choose Workstation"
        if ! WORKSTATION=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 2 "desktop" "Desktop" "notebook" "Notebook" 3>&1 1>&2 2>&3); then
            exit 0
        fi

        core_replace_config_value "HOSTNAME" "$USERNAME-$WORKSTATION"
        core_replace_config_value "WORKSTATION" "$WORKSTATION"
    fi

    #----------------------------------------
    # Check Language
    #----------------------------------------
    if [ "$LOCALE_LANG" = "" ] || [ ${#LOCALE_GEN[@]} = 0 ] || [ "$TIMEZONE" = "" ] || [ "$VCONSOLE_KEYMAP" = "" ] || [ "$X11_KEYBOARD_LAYOUT" = "" ] || [ "$X11_KEYBOARD_VARIANT" = "" ]; then

        tui_init 20 "Choose Setup Language"
        if ! lang_result=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 2 "en_US" "English" "de_DE" "German" 3>&1 1>&2 2>&3); then
            exit 0
        fi
        if [ "$lang_result" = "en_US" ]; then
            set_lang_en_US
        fi

        if [ "$lang_result" = "de_DE" ]; then
            set_lang_de_DE
        fi

        core_replace_config_value "TIMEZONE" "$TIMEZONE"
        core_replace_config_value "LOCALE_LANG" "$LOCALE_LANG"
        core_replace_config_array "LOCALE_GEN" "${LOCALE_GEN[@]}"
        core_replace_config_value "VCONSOLE_KEYMAP" "$VCONSOLE_KEYMAP"
        core_replace_config_value "X11_KEYBOARD_LAYOUT" "$X11_KEYBOARD_LAYOUT"
        core_replace_config_value "X11_KEYBOARD_VARIANT" "$X11_KEYBOARD_VARIANT"
    fi

    #----------------------------------------
    # Check Microcode
    #----------------------------------------
    if [ "$UCODE" = "" ]; then

        tui_init 18 "Choose Processor Microcode"
        if ! UCODE=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3 "none" "Disable" "intel-ucode" "Intel" "amd-ucode" "AMD" 3>&1 1>&2 2>&3); then
            exit 0
        fi
        if [ "$UCODE" = 'none' ]; then
            UCODE=''
        fi

        core_replace_config_value "UCODE" "$UCODE"
    fi

    #----------------------------------------
    # Check disk
    #----------------------------------------
    core_tui_check_disk
    core_replace_config_value "DISK" "$DISK"
    core_replace_config_value "BOOT_PARTITION" "$BOOT_PARTITION"
    core_replace_config_value "ROOT_PARTITION" "$ROOT_PARTITION"

    #----------------------------------------
    # Add default values
    #----------------------------------------
    core_check_config_key "SWAP_SIZE" "$SWAP_SIZE"
    core_check_config_key "CUSTOM_PACKAGES" "$CUSTOM_PACKAGES"

    #----------------------------------------
    # Show default config screen
    #----------------------------------------
    tui_init 0 "$(cat "$CORE_CONFIG_FILE")"
    tui_add 28 "\nEdit Setup Configuration?"
    if (whiptail --yesno "$(cat "$SCRIPT_TUI_FILE")" 0 "$SCRIPT_TUI_WIDTH"); then
        nano "$CORE_CONFIG_FILE"
        wait
        # Check again after edit
        core_tui_check_config
    fi

    #----------------------------------------
    # Source changes
    #----------------------------------------
    . "$CORE_CONFIG_FILE"
}

core_reset_config() {

    core_log "Reset core configuration"

    # Reset config
    if [ -f "$CORE_CONFIG_FILE" ]; then
        mv -f "$CORE_CONFIG_FILE" "$CORE_CONFIG_FILE"".backup"
    fi

    # Reset logs
    if [ -f "$CORE_LOG_FILE" ]; then
        mv -f "$CORE_LOG_FILE" "$CORE_LOG_FILE"".backup"
    fi

    # Unmount
    swapoff -a
    umount -R /mnt
    cryptsetup close cryptroot

    core_log "Reset finished!"
}

core_log() {

    touch "$CORE_LOG_FILE"

    # Default vaules
    local lvl="INFO"
    local text="$1"

    # Handle if 2. parameter is set
    if [ "$2" != "" ]; then

        if [ "$1" = "c" ]; then
            lvl="EXEC"
        fi

        if [ "$1" = "e" ]; then
            lvl="FAIL"
        fi

        # Shift to 2. argument to you $* for all instead of $2
        shift
        text="$*"
    fi

    # Style log output
    local styled_text="$(date "+%Y-%m-%d %H:%M:%S") $SCRIPT_ID-$SCRIPT_VERSION | $lvl | $text"

    # Print to STOUT & CORE_LOG_FILE
    printf '%s\n' "$styled_text" >>"$CORE_LOG_FILE"
    printf '%s\n' "$styled_text"
}

core_exec_command_wrap() {
    # !!! DO NOT USE WITH PIPE (|) OR REDIRECT (>>) !!!

    local command_txt="$*"
    local tmp_error="$SCRIPT_DIR/$SCRIPT_ID.error"

    if "$@" >/dev/null 2>"$tmp_error"; then
        core_log "c" "$command_txt"
        rm -f "$tmp_error"
        return 0
    else
        core_log "e" "$command_txt"
        cat "$tmp_error" >>"$CORE_LOG_FILE"
        cat "/mnt/$SCRIPT_ID.log" >>"$CORE_LOG_FILE"
        rm -f "$tmp_error"
        exit 1
    fi
}

core_gauge_update() {
    local percent="$1"
    local text="$2"
    tui_init 0 "$text"
    echo -e "XXX\n$percent\n$(cat "$SCRIPT_TUI_FILE")\nXXX"
}

core_check_config_key() {
    local config_key="$1"
    local config_value="$2"
    touch "$CORE_CONFIG_FILE"
    if ! grep -qrnw "$CORE_CONFIG_FILE" -e "$config_key=*"; then
        echo "$config_key=\"$config_value\"" >>"$CORE_CONFIG_FILE"
    fi
}

core_replace_config_value() {
    local key=$1
    local value=$2
    core_check_config_key "$key" "$value"
    sed -i "s#$key=.*#$key=\"$value\"#g" "$CORE_CONFIG_FILE"
}

core_replace_config_array() {
    local key=$1 && shift
    local value=("$@")

    local items_txt='( '
    for item in "${value[@]}"; do
        items_txt="$items_txt'$item' "
    done
    items_txt="$items_txt"')'

    core_check_config_key "$key" ""
    sed -i "s#$key=.*#$key=$items_txt#g" "$CORE_CONFIG_FILE"
}

#/////////////////////////////////////////////////////
# ECOS INSTALLATION
#/////////////////////////////////////////////////////

ecos_check_git() {
    if ! pacman -Qi git >/dev/null; then
        echo "Create Git config"
        mkdir -p "$HOME/.config/git"
        if [ -f "$HOME/.config/git/config" ]; then
            mv "$HOME/.config/git/config" "$HOME/.config/git/config.bak"
        fi
        {
            echo "[user]"
            echo "    email = ${USER}@$(cat /etc/hostname)"
            echo "    name = ${USER}"
            echo "[credential]"
            echo "    helper = /usr/lib/git-core/git-credential-libsecret"
            echo "[pull]"
            echo "    rebase = false"
        } >"$HOME/.config/git/config"

        echo "Install Git"
        sudo pacman --noconfirm --needed -Syyu git
    fi
}

ecos_check_paru() {
    if ! pacman -Qi paru >/dev/null; then
        echo "Installing AUR Helper Paru (may take a while)..."

        # Prepare
        local paru_build_tmp="$HOME/Downloads/paru"
        rm -rf "$paru_build_tmp"
        mkdir -p "$paru_build_tmp"

        # Clone
        ecos_check_git
        git clone "https://aur.archlinux.org/paru-bin.git" "$paru_build_tmp"
        cd "$paru_build_tmp" || exit 1

        # Install aur helper
        makepkg -si --noconfirm --needed

        # Remove download dir
        rm -rf "$paru_build_tmp"

        # Symlink to yay
        sudo ln -sf /usr/bin/paru /usr/bin/yay

        # Config
        sudo sed -i 's/^#BottomUp/BottomUp/g' /etc/paru.conf
        sudo sed -i 's/^#SudoLoop/SudoLoop/g' /etc/paru.conf
    fi
}

ecos_create_desktop_file() {
    mkdir -p "$HOME/.local/share/applications/"
    {
        echo "[Desktop Entry]"
        echo "Name=ECOS"
        echo "Icon=ecos"
        echo 'Exec=gnome-terminal -- bash -c $HOME/.ecos/bin/ecos'
        echo "Type=Application"
    } >"$ECOS_DESKTOP_FILE"
    chmod +x "$ECOS_DESKTOP_FILE"
}

ecos_tui_install_ecos() {

    check_internet

    # Create dirs
    mkdir -p "$ECOS_WORKING_DIR"
    mkdir -p "$ECOS_USER_TWEAKS"

    tui_init 0 "Dotfiles URL"
    if ! ECOS_DOTS_DEFAULT_URL=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "$ECOS_DOTS_DEFAULT_URL" 3>&1 1>&2 2>&3); then
        main
        exit 0
    fi
    if [ "$ECOS_DOTS_DEFAULT_URL" = "" ]; then
        tui_init 0 "Dotfiles URL was empty!"
        whiptail --textbox "$SCRIPT_TUI_FILE" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH"
        return
    fi

    clear
    print_header

    print_title "INSTALL ECOS CORE"
    ecos_update_core
    echo -e "DONE"

    print_title "CHECK GIT"
    ecos_check_git
    echo -e "DONE"

    print_title "CHECK PARU"
    ecos_check_paru
    echo -e "DONE"

    print_title "UPDATE ECOS REPO"
    ecos_update_cache_repo
    echo -e "DONE"

    print_title "CLONE DOTFILES"
    rm -rf "$ECOS_LOCAL_DOTFILES"
    mkdir -p "$ECOS_LOCAL_DOTFILES"
    cd "$HOME" || exit 1

    # Removing existing init
    if [ -f "$ECOS_INIT" ]; then
        "$ECOS_INIT" --remove
    fi

    # Clone dotfiles
    git clone --bare "$ECOS_DOTS_DEFAULT_URL" "$ECOS_LOCAL_DOTFILES"

    # Reset dotfiles
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" fetch --all
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" reset --hard HEAD
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" config --local status.showUntrackedFiles no

    echo -e "DONE"

    print_title "INIT DOTFILES"
    if [ ! -f "$ECOS_INIT" ]; then
        echo "ERROR: $ECOS_INIT not found"
        exit 1
    fi

    # Call init script
    echo -e "EXECUTE $ECOS_INIT"
    chmod +x "$ECOS_INIT" && "$ECOS_INIT" --install

    # Silent Boot
    echo '# Disable the last login message on startup with this file' >"$HOME/.hushlogin"

    # GnuPG conf
    mkdir -p "$HOME/.local/share/gnupg"
    echo 'pinentry-program /usr/bin/pinentry-gnome3' >"$HOME/.local/share/gnupg/gpg-agent.conf"

    # Set correct gnupg permission
    chmod -R go-rwx "$HOME/.local/share/gnupg"

    # Create initialized state file
    echo "$SCRIPT_VERSION" >"$ECOS_INITIALIZED"
    touch "$ECOS_SHOW_CHANGELOG"
    echo -e "DONE"

    # Create Desktop file
    print_title 'CREATE ECOS DESKTOP FILE'
    ecos_create_desktop_file
    echo -e "DONE"

    print_title "ECOS INSTALLATION FINISHED"
    read -p 'Please REBOOT NOW! Close with any Key...'
    wait
    exit 0
}

#/////////////////////////////////////////////////////
# UPDATE
#/////////////////////////////////////////////////////

ecos_update_cache_repo() {

    mkdir -p "$ECOS_CACHE_REPO_ECOS"
    if ! [ -d "$ECOS_CACHE_REPO_ECOS/.git" ]; then
        git clone "$ECOS_REPO_URL" "$ECOS_CACHE_REPO_ECOS"
    fi

    cd "$ECOS_CACHE_REPO_ECOS" || exit 1
    git fetch --all
    git reset --hard origin/HEAD
    git clean -d -f
    git pull

    # Add user tweaks
    if [ -d "$ECOS_USER_TWEAKS" ]; then

        readarray -d '' user_tweaks_list < <(find "$ECOS_USER_TWEAKS" -mindepth 1 -maxdepth 1 -type d -print0)

        for i in "${user_tweaks_list[@]}"; do

            local tweak_id="$(basename $i)"
            local tweak_sh="$ECOS_USER_TWEAKS/$tweak_id/${tweak_id}.sh"

            # Check sh file
            if ! [ -f "$tweak_sh" ]; then
                continue
            fi

            #Copy User tweaks
            cp -r "$ECOS_USER_TWEAKS/$tweak_id" "$ECOS_CACHE_REPO_ECOS/tweaks/$tweak_id"
        done
    fi
}

ecos_update_core() {

    check_internet

    # Make dirs
    mkdir -p "$ECOS_HOME"
    mkdir -p "$ECOS_WORKING_DIR"
    mkdir -p "$ECOS_BIN_DIR"
    mkdir -p "$ECOS_USER_TWEAKS"
    mkdir -p "$HOME/.local/share/applications"

    local tmp_ecos="$ECOS_WORKING_DIR/ecos-new"
    if ! curl -s -L "$ECOS_CORE_URL" >"$tmp_ecos"; then
        echo "ERROR: ECOS CORE DOWNLOAD"
        exit 1
    fi
    if [ ! -f "$tmp_ecos" ]; then
        echo "ERROR: ECOS UPDATE FILE NOT FOUND"
        exit 1
    else
        mv "$tmp_ecos" "$ECOS_CORE"
    fi
    if ! chmod +x "$ECOS_CORE"; then
        echo "ERROR: ECOS CORE NOT FOUND"
        exit 1
    fi
}

ecos_update_system() {

    clear
    print_header
    check_internet

    print_title 'CHECK ECOS DEPENDENCIES'
    ecos_check_git
    ecos_check_paru
    echo ">>> OK"

    print_title 'UPDATE ECOS REPO'
    ecos_update_cache_repo
    echo ">>> OK"


    # DOTFILES UPDATE
    print_title 'ECOS DOTFILES UPDATE'
    cd "$HOME"

    # RESET LOCAL FILES
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" fetch --all
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" reset --hard HEAD
    git --git-dir="$ECOS_LOCAL_DOTFILES" --work-tree="$HOME" pull

    # PACKAGE UPDATE
    print_title 'FETCH PACKAGE UPDATES'
    paru -Syy

    # PACKAGE UPGRADE
    print_title 'UPGRADE SYSTEM PACKAGES'
    paru -Qu
    echo ''
    read -p "Upgrade packages? [y/n]: " user_input
    if [ "$user_input" = "y" ]; then
        if ! paru -Su --noconfirm; then
            echo -e "ERROR: paru"
            exit 1
        fi
        wait

    else
        echo "Skipped..."
    fi

    # UPDATE TWEAKS
    print_title 'UPDATING ECOS TWEAKS'
    ecos_update_tweaks

    # UPDATE INIT FILE
    if [ -f "$ECOS_INIT" ]; then
        latest_changelog_version=""
        if [ -f "$ECOS_INITIALIZED" ]; then
            latest_changelog_version=$(<"$ECOS_INITIALIZED")
        fi
        if [ "$SCRIPT_VERSION" != "$latest_changelog_version" ]; then
            print_title 'REINSTALL ECOS INIT FILE'
            "$ECOS_INIT" --install
            echo "$SCRIPT_VERSION" >"$ECOS_INITIALIZED"
            touch "$ECOS_SHOW_CHANGELOG"
        else
            print_title 'UPDATING ECOS INIT FILE'
            "$ECOS_INIT" --update
        fi
    fi

    # UPDATE DESKTOP FILE
    print_title 'UPDATE ECOS FILES'

    # Create desktop file
    ecos_create_desktop_file

    # Create dots bin
    local dots_bin="$ECOS_BIN_DIR/dots"
    echo '#!/bin/sh' >"$dots_bin"
    echo 'git --git-dir="'$ECOS_LOCAL_DOTFILES'" --work-tree="$HOME" "$@"' >>"$dots_bin"
    chmod +x "$dots_bin"

    echo ">>> OK"

    # FINISH
    print_title 'ECOS UPDATE FINISHED'
    echo ""
    read -p "Press any Key to close..."
    exit 0
}

#/////////////////////////////////////////////////////
# TWEAKS
#/////////////////////////////////////////////////////

ecos_tui_menu_tweaks() {

    ecos_check_git
    ecos_check_paru
    ecos_update_cache_repo

    local tweaks_array_all=()
    local tweaks_array_enabled=()
    local tweaks_array_disabled=()
    local tweak_dir_list=()

    #----------------------------------------
    # READ TWEAK LIST
    #----------------------------------------
    readarray -d '' tweak_dir_list < <(find "$ECOS_CACHE_REPO_ECOS/tweaks" -mindepth 1 -maxdepth 1 -type d -print0)

    for i in "${tweak_dir_list[@]}"; do

        local tweak_id="$(basename $i)"
        local tweak_sh="$ECOS_CACHE_REPO_ECOS/tweaks/$tweak_id/${tweak_id}.sh"
        local tweak_meta="$ECOS_CACHE_TWEAKS/$tweak_id/${tweak_id}.tweak"

        # Check sh file
        if ! [ -f "$tweak_sh" ]; then
            continue
        fi

        # Check if installed
        if [ -f "$tweak_meta" ]; then
            # Add to enabled
            tweaks_array_enabled+=("$tweak_id")
        else
            # Add to disabled
            tweaks_array_disabled+=("$tweak_id")
        fi

        # Add to all
        tweaks_array_all+=("$tweak_id")
    done

    #echo "ALL: ${tweaks_array_all[@]}"
    #echo "ENABLED: ${tweaks_array_enabled[@]}"
    #echo "DISABLED: ${tweaks_array_disabled[@]}"

    #----------------------------------------
    # TUI SELECT TWEAK ACTION
    #----------------------------------------
    tui_init 28 "TWEAKS"
    local tweaks_info="                             ${#tweaks_array_enabled[@]}/${#tweaks_array_all[@]}"
    local tweak_action_input=$(whiptail --menu --notags "$(cat "$SCRIPT_TUI_FILE")\n\n$tweaks_info" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 3 "install" "Install" "update" "Update" "remove" "Remove" 3>&1 1>&2 2>&3)
    if [ "$tweak_action_input" = "" ]; then
        main
        exit 0
    fi

    local selected_tweaks_array=()
    local tweak_status='off'

    if [ "$tweak_action_input" = "install" ]; then
        tweak_status='off'
        selected_tweaks_array=("${tweaks_array_disabled[@]}")
    fi
    if [ "$tweak_action_input" = "update" ]; then
        tweak_status='on'
        selected_tweaks_array=("${tweaks_array_enabled[@]}")
    fi
    if [ "$tweak_action_input" = "remove" ]; then
        tweak_status='off'
        selected_tweaks_array=("${tweaks_array_enabled[@]}")
    fi

    #----------------------------------------
    # CREATE WHIPTAIL ARRAY
    #----------------------------------------
    local whiptail_tweaks_array=()
    for i in "${selected_tweaks_array[@]}"; do
        local tweak_id="$i"
        whiptail_tweaks_array+=("${tweak_id} ${tweak_id} ${tweak_status}")
    done

    #----------------------------------------
    # TUI TWEAK LIST
    #----------------------------------------
    tui_init 0 ""
    local menu_input=$(whiptail --checklist --notags "$(cat "$SCRIPT_TUI_FILE")\n\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" 10 ${whiptail_tweaks_array[@]} 3>&1 1>&2 2>&3)
    if [ "$menu_input" = "" ]; then
        main
        exit 0
    fi

    local selected_array=($(echo "$menu_input" | tr -d '"'))
    clear
    echo "SELECTED TWEAKS: ${selected_array[@]}"

    #----------------------------------------
    # EXECUTE TWEAK LIST
    #----------------------------------------
    for i in "${selected_array[@]}"; do
        ecos_exec_tweak "$tweak_action_input" "$i"
        wait
    done

    # Return to tui
    ecos_tui_menu_tweaks
}

ecos_exec_tweak() {

    local tweak_action="$1"
    local tweak_id="$2"
    local tweak_res_dir="$ECOS_CACHE_REPO_ECOS/tweaks/$tweak_id"
    local tweak_cache_dir="$ECOS_CACHE_TWEAKS/$tweak_id"
    local tweak_sh="$tweak_res_dir/${tweak_id}.sh"
    local tweak_meta="$tweak_cache_dir/${tweak_id}.tweak"

    #----------------------------------------
    # Check
    #----------------------------------------
    if [ "$tweak_id" = "" ]; then
        echo -e "Error: Tweak ID is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
        exit 1
    fi

    if [ "$tweak_action" = "" ]; then
        echo -e "Error: TWEAK_ACTION is empty.\nExecute with:\n$ECOS_CORE --tweak TWEAK_ACTION TWEAK_ID"
        exit 1
    fi

    #----------------------------------------
    # Execute Tweak
    #----------------------------------------
    if [ "$tweak_action" = "install" ] || [ "$tweak_action" = "remove" ] || [ "$tweak_action" = "update" ]; then
        print_title "TWEAK | $tweak_action: $tweak_id"
        if ! [ -f "$tweak_sh" ]; then
            echo "Error: $tweak_id not exists ($tweak_sh)"
            return 1
        fi

        # Create tweak cache dir
        mkdir -p "$tweak_cache_dir"

        # Execute tweak
        chmod +x "$tweak_sh"
        cd "$tweak_cache_dir" || exit 1
        ECOS_HOME=$ECOS_HOME $tweak_sh $tweak_action $tweak_res_dir $tweak_cache_dir

        # Install or update
        if [ "$tweak_action" = "install" ] || [ "$tweak_action" = "update" ]; then
            echo "$(date "+%Y-%m-%d-%H:%M:%S")" >"$tweak_meta"
        fi

        # Remove
        if [ "$tweak_action" = "remove" ]; then
            rm -rf "$tweak_cache_dir"
        fi
    else
        echo "Error: TWEAK_ACTION=$tweak_action not supported"
    fi
}

ecos_update_tweaks() {
    local tweak_dir_list=()
    ecos_update_cache_repo
    readarray -d '' tweak_dir_list < <(find "$ECOS_CACHE_TWEAKS" -mindepth 1 -maxdepth 1 -type d -print0)
    for i in "${tweak_dir_list[@]}"; do
        local tweak_id="$(basename $i)"
        local tweak_sh="$ECOS_CACHE_REPO_ECOS/$tweak_id/${tweak_id}.sh"
        ecos_exec_tweak "update" "$tweak_id"
    done
}

#/////////////////////////////////////////////////////
# CREATE USB STICK
#/////////////////////////////////////////////////////

tui_create_usb() {

    if ! [ -x "$(command -v whiptail)" ]; then
        echo "ERROR: whiptail not installed"
        exit 1
    fi

    if ! [ -x "$(command -v curl)" ]; then
        echo "ERROR: curl not installed"
        exit 1
    fi

    if ! [ -x "$(command -v dd)" ]; then
        echo "ERROR: dd not installed"
        exit 1
    fi

    # Select Disk
    #--------------------------------------------
    disk_array=()
    while read disk_line; do
        disk_size=$(lsblk -d -n -o SIZE /dev/$disk_line)
        disk_array+=("/dev/$disk_line")
        disk_array+=(" ($disk_size)")
    done < <(lsblk -I 8 -d -o KNAME -n)

    usb_disk=''
    tui_init 11 "Choose USB Stick for ECOS Installation"
    if ! usb_disk=$(whiptail --menu "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "${#disk_array[@]}" "${disk_array[@]}" 3>&1 1>&2 2>&3); then
        main
        exit 0
    fi
    tui_init 0 "Arch ISO URL"
    if ! ECOS_ARCH_ISO_DEFAULT_URL=$(whiptail --inputbox "$(cat "$SCRIPT_TUI_FILE")\n" "$SCRIPT_TUI_HEIGHT" "$SCRIPT_TUI_WIDTH" "$ECOS_ARCH_ISO_DEFAULT_URL" 3>&1 1>&2 2>&3); then
        main
        exit 0
    fi
    if [ "$ECOS_ARCH_ISO_DEFAULT_URL" = "" ]; then
        echo "URL was empty"
        main
        exit 1
    fi

    print_header
    print_title "USB Disk: $usb_disk"
    echo -e '\n'
    print_title "ARCH URL: $ECOS_ARCH_ISO_DEFAULT_URL"

    # Check and download arch iso
    #--------------------------------------------
    mkdir -p "$ECOS_WORKING_DIR"
    if ! [ -f "$ECOS_ARCH_ISO_FILE" ]; then
        print_title "Downloading $ECOS_ARCH_ISO_FILE from $ECOS_ARCH_ISO_DEFAULT_URL..."

        if ! curl -L "$ECOS_ARCH_ISO_DEFAULT_URL" -o "$ECOS_ARCH_ISO_FILE.part"; then
            echo "ERROR: Downloading ISO"
            exit 1
        fi
        wait

        if ! mv "$ECOS_ARCH_ISO_FILE.part" "$ECOS_ARCH_ISO_FILE"; then
            echo "ERROR: Moving ISO file"
            exit 1
        fi
    fi

    print_title "Arch ISO: $ECOS_ARCH_ISO_FILE"

    # Create Bootable USB Stick
    #--------------------------------------------
    print_title "// Create Bootable USB Stick"

    if ! sudo dd bs=4M if="$ECOS_ARCH_ISO_FILE" of="$usb_disk" status=progress oflag=sync; then
        echo "ERROR: Creating USB Stick"
        exit 1
    fi
    wait

    # Unmount
    #--------------------------------------------
    print_title "Unmount USB Stick"
    sudo umount -R "$usb_disk"
    wait

    print_title "FINISHED! Please remove the USB Stick $usb_disk"
}

#/////////////////////////////////////////////////////
# RECOVERY
#/////////////////////////////////////////////////////

tui_open_recovery() {

    #----------------------------------------
    # Select Disk
    #----------------------------------------
    core_tui_check_disk --force

    #----------------------------------------
    # Open Crypt
    #----------------------------------------
    clear
    print_header
    print_title "OPEN CRYPTED: $ROOT_PARTITION"
    echo -e "\nENTER YOUR ENCRYPTION PASSWORD\n"
    cryptsetup open $ROOT_PARTITION cryptroot

    #----------------------------------------
    # Mount
    #----------------------------------------
    local mnt_recovery='/mnt/recovery'
    print_title "MOUNT TO $mnt_recovery"
    mkdir -p "$mnt_recovery"
    mount /dev/mapper/cryptroot "$mnt_recovery"
    mkdir -p "$mnt_recovery/boot"
    mount -p "$BOOT_PARTITION" "$mnt_recovery/boot"

    #----------------------------------------
    # Chroot
    #----------------------------------------
    clear
    print_header
    print_title "ECOS RECOVERY"

    # Mount /boot in recovery system
    if ! arch-chroot "$mnt_recovery" mount $BOOT_PARTITION /boot; then
        echo "CHROOT Mount /boot"
        exit 1
    fi
    echo -e "\n"
    echo -e "!! YOUR ARE NOW ON YOUR RECOVERY SYSTEM !!"
    echo -e "        Leave with command 'exit'         "
    echo -e "\n"
    arch-chroot "$mnt_recovery"
    wait

    #----------------------------------------
    # Unmount
    #----------------------------------------
    clear
    print_header
    print_title "UNMOUNT"
    swapoff -a
    umount -R "$mnt_recovery"
    cryptsetup close cryptroot
}

#/////////////////////////////////////////////////////
# HELPER
#/////////////////////////////////////////////////////

tui_init() {
    rm -f "$SCRIPT_TUI_FILE"
    echo '
             ███████╗ ██████╗ ██████╗ ███████╗
             ██╔════╝██╔════╝██╔═══██╗██╔════╝
             █████╗  ██║     ██║   ██║███████╗
             ██╔══╝  ██║     ██║   ██║╚════██║
             ███████╗╚██████╗╚██████╔╝███████║
             ╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝
                                       v.'$SCRIPT_VERSION'
    ' >"$SCRIPT_TUI_FILE"
    tui_add "$1" "$2"
}

tui_add() {

    echo_whitespaces() {
        #----------------------------------------
        # Echo a string with leading spaces
        #   $1: number of spaces
        #   $2: string
        #----------------------------------------
        local spaces=""
        for i in $(seq 1 "$1"); do
            spaces=" ${spaces}"
        done
        echo -e "$spaces""$2"
    }

    echo -e "$(echo_whitespaces "$1" "$2")\n" >>"$SCRIPT_TUI_FILE"
}

print_header() {
    echo '
    ███████╗ ██████╗ ██████╗ ███████╗
    ██╔════╝██╔════╝██╔═══██╗██╔════╝
    █████╗  ██║     ██║   ██║███████╗
    ██╔══╝  ██║     ██║   ██║╚════██║
    ███████╗╚██████╗╚██████╔╝███████║
    ╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝
                              v.'$SCRIPT_VERSION''
}

print_title() {
    echo -e "\n"
    echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    echo -e "> $1"
    echo -e ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
}

check_internet() {
    # curl -Is "http://www.google.com" | head -1 | grep 200 >/dev/null
    if ! ping archlinux.de -c 1 >/dev/null 2>&1; then
        tui_init 0 "Error: No Internet Connection!"
        whiptail --msgbox "$(cat "$SCRIPT_TUI_FILE")" 0 "$SCRIPT_TUI_WIDTH"
        exit 1
    fi
}

#/////////////////////////////////////////////////////
# TRAP
#/////////////////////////////////////////////////////

on_trap() {
    rm -f "$SCRIPT_TUI_FILE"
}

# Set trap
trap 'on_trap' 0 1 3 6

#/////////////////////////////////////////////////////
# EXECUTE
#/////////////////////////////////////////////////////

main "$@"
