#!/bin/bash

#/////////////////////////////////////////////////////
# SOURCES
#/////////////////////////////////////////////////////

# https://wiki.archlinux.de/title/Installation_mit_UEFI_und_Verschl%C3%BCsselung
# https://www.timoschindler.de/arch-linux-uefi-boot-mit-grub-und-verschluesseltem-lvm/
# https://wiki.archlinux.de/title/GRUB

#/////////////////////////////////////////////////////
# VARIABLES
#/////////////////////////////////////////////////////

# SCRIPT VARIABLES
INSTALLER_ID="ecos-installer"
INSTALLER_WORKING_DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
INSTALLER_SCRIPT_FILE="$INSTALLER_WORKING_DIR/$(basename "$0")"
INSTALLER_CONFIG_FILE="$INSTALLER_WORKING_DIR/$INSTALLER_ID.conf"
INSTALLER_LOG_FILE="$INSTALLER_WORKING_DIR/$INSTALLER_ID.log"
UEFI_ENABLED=''

# DEFAULT PASSWORD
ECOS_DEFAULT_PASSWORD='ecos'

# PROGRES
PROGRESS_FILE="$INSTALLER_WORKING_DIR/$INSTALLER_ID.progress"

# TUI VARIABLES
TUI_FILE="$INSTALLER_WORKING_DIR/$INSTALLER_ID.tui"
TUI_WIDTH=64
TUI_HEIGHT=24

# ECOS URL
ECOS_REPO_URL="https://github.com/murkl/ecos.git"

# ARCH ISO
ECOS_ARCH_ISO_ROOT_URL="https://www.archlinux.de/download/iso/$(date "+%Y.%m.01")"
ECOS_ARCH_ISO_FILE="archlinux-$(date "+%Y.%m.01")-x86_64.iso"
ECOS_ARCH_ISO_SHA1="sha1sums.txt"

# TERMINAL COLORS
TERM_COLOR_RED='\033[0;31m'
TERM_COLOR_GREEN='\033[1;32m'
TERM_COLOR_BLUE='\033[1;34m'
TERM_COLOR_PURPLE='\033[1;35m'
TERM_COLOR_YELLOW='\033[1;33m'
TERM_COLOR_NULL='\033[0m' # No Color

# INSTALLER CONFIGURATION
USERNAME=''
HOSTNAME=''
WORKSTATION=''
SWAP_SIZE='0'
DISK=''
BOOT_PARTITION=''
ROOT_PARTITION=''
UCODE=''
LOCALE_LANG=''
LOCALE_GEN=('')
TIMEZONE=''
VCONSOLE_KEYMAP=''
BOOT_ARGS=''
X11_KEYBOARD_LAYOUT=''
X11_KEYBOARD_VARIANT=''
DUALBOOT='default' # windows10
BOOTLOADER='grub'  # systemd
BOOTLOADER_RESOLUTION='1024x768x32'
WIPE_DISK='false'
AUTO_UNMOUNT='true'
CUSTOM_PACKAGES=''

#/////////////////////////////////////////////////////
# INSTALLER LANGUAGES
#/////////////////////////////////////////////////////

set_lang_en_US() {
    TIMEZONE='Europe/Berlin'
    LOCALE_LANG='en_US.UTF-8'
    LOCALE_GEN=('en_US.UTF-8 UTF-8')
    VCONSOLE_KEYMAP='en-latin1-nodeadkeys'
    X11_KEYBOARD_LAYOUT='en'
    X11_KEYBOARD_VARIANT='nodeadkeys'
    BOOT_ARGS="lang=en locale=en_US.UTF-8"
}

set_lang_de_DE() {
    TIMEZONE='Europe/Berlin'
    LOCALE_LANG='de_DE.UTF-8'
    LOCALE_GEN=('de_DE.UTF-8 UTF-8' 'de_DE ISO-8859-1' 'de_DE@euro ISO-8859-15' 'en_US.UTF-8 UTF-8')
    VCONSOLE_KEYMAP='de-latin1-nodeadkeys'
    X11_KEYBOARD_LAYOUT='de'
    X11_KEYBOARD_VARIANT='nodeadkeys'
    BOOT_ARGS="lang=de locale=de_DE.UTF-8"
}

#/////////////////////////////////////////////////////
# MAIN
#/////////////////////////////////////////////////////

main() {

    #----------------------------------------
    # PRINT VERSION
    #----------------------------------------
    if [ "$1" = "--version" ]; then
        echo -e "$VERSION"
        exit 0
    fi

    #----------------------------------------
    # CHROOT INSTALLER
    #----------------------------------------
    if [ "$1" = "--chroot" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
        exec_install_chroot "$2" "$3"
        exit $?
    fi

    # ---------------------------------------
    # FORCE: INSTALL ECOS CORE
    # ---------------------------------------
    if [ "$1" = "--core" ]; then
        tui_core_installer_menu
        exit $?
    fi

    # ---------------------------------------
    # FORCE: CREATE BOOTABLE USB
    # ---------------------------------------
    if [ "$1" = "--usb" ]; then
        tui_create_usb
        exit $?
    fi

    # ---------------------------------------
    # AUTO DETECT
    # ---------------------------------------
    if [ "$1" = "" ]; then
        # Check if started from arch live iso
        if [ -f "/proc/sys/kernel/hostname" ] && [ "$(cat /proc/sys/kernel/hostname)" = "archiso" ]; then
            tui_core_installer_menu
        else
            tui_create_usb
        fi
    fi
}

#/////////////////////////////////////////////////////
# TUI CORE INSTALLER
#/////////////////////////////////////////////////////

tui_core_installer_menu() {

    #----------------------------------------
    # Reset logfile
    #----------------------------------------
    mv -f "$INSTALLER_LOG_FILE" "$INSTALLER_LOG_FILE"".backup"

    #----------------------------------------
    # Check UEFI boot
    #----------------------------------------
    [ -d /sys/firmware/efi ] && UEFI_ENABLED='true' || UEFI_ENABLED='false'
    # if [ -x "$(command -v efivar)" ] && [ "$(efivar -l >/dev/null)" != "" ]; then
    #if [ -x "$(command -v efivar)" ] && [ "$(efivar -l >/dev/null)" != "" ]; then; fi

    core_log "UEFI MODE: $UEFI_ENABLED"

    #----------------------------------------
    # Show TUI menu
    #----------------------------------------
    tui_init 0 ""
    if ! menu_input=$(whiptail --menu --notags "$(cat "$TUI_FILE")\n\n" "$TUI_HEIGHT" "$TUI_WIDTH" 3 "1" "Install ECOS Core" "2" "    Recovery" "3" "      Logs" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    #----------------------------------------
    # Install core
    #----------------------------------------
    if [ "$menu_input" = "1" ]; then
        tui_install_ecos_core "$UEFI_ENABLED"
        exit $?
    fi

    #----------------------------------------
    # Recovery
    #----------------------------------------
    if [ "$menu_input" = "2" ]; then
        tui_open_recovery "$UEFI_ENABLED"
        tui_core_installer_menu
        exit 0
    fi

    #----------------------------------------
    # Logs
    #----------------------------------------
    if [ "$menu_input" = "3" ]; then
        tui_show_logs
        tui_core_installer_menu
        exit 0
    fi
}

#/////////////////////////////////////////////////////
# TUI CORE INSTALLER
#/////////////////////////////////////////////////////

tui_install_ecos_core() {

    local uefi_mode="$1"

    #----------------------------------------
    # Ask for reset core config
    #----------------------------------------
    if [ -f "$INSTALLER_CONFIG_FILE" ]; then
        tui_init 15 "Continue Setup Configuration?\n"
        if ! (whiptail --yesno "$(cat "$TUI_FILE")" 0 "$TUI_WIDTH"); then
            core_log "Reset core configuration"

            # Reset config
            if [ -f "$INSTALLER_CONFIG_FILE" ]; then
                mv -f "$INSTALLER_CONFIG_FILE" "$INSTALLER_CONFIG_FILE"".backup"
            fi

            # Reset logs
            if [ -f "$INSTALLER_LOG_FILE" ]; then
                mv -f "$INSTALLER_LOG_FILE" "$INSTALLER_LOG_FILE"".backup"
            fi

            core_log "Reset successfully!"
        fi
    fi

    #----------------------------------------
    # Check config
    #----------------------------------------
    check_config

    #----------------------------------------
    # Encryption password
    #----------------------------------------
    tui_init 0 "Enter Encryption Password"
    if ! password_encryption=$(whiptail --passwordbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH" 3>&1 1>&2 2>&3); then
        tui_core_installer_menu
        exit 0
    fi

    # Confirm password
    tui_init 0 "Confirm Encryption Password"
    if ! password_input_confirm=$(whiptail --passwordbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH" 3>&1 1>&2 2>&3); then
        tui_core_installer_menu
        exit 0
    fi

    # Check password
    if [ "$password_encryption" != "$password_input_confirm" ]; then
        tui_init 0 "Password Mismatch! Restart the Installation..."
        whiptail --msgbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH"
        tui_core_installer_menu
        exit 0
    fi

    #----------------------------------------
    # Confirm and execute install
    #----------------------------------------
    tui_init 0 "Start Installation"
    tui_add 0 "!!! ALL YOUR DATA WILL BE LOST !!!"
    tui_add 0 "Continue?"
    if (! whiptail --yesno "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH"); then
        tui_core_installer_menu
        exit 0
    fi

    #----------------------------------------
    # Execute install (will execute chroot)
    #----------------------------------------
    tui_init 0 "Core Installation..."
    exec_install_core "$uefi_mode" "$password_encryption" "$PROGRESS_FILE" | whiptail --gauge "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH" 0 3>&1 1>&2 2>&3
    wait

    # Finish
    local progress_status=$(<"$PROGRESS_FILE")
    rm -rf "$PROGRESS_FILE"

    if [ "$progress_status" = "PROGRESS_SUCCESS" ]; then

        # Success message
        tui_init 0 "INSTALLATION SUCCESSFULLY FINISHED"
        whiptail --msgbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH"

        # Logs
        tui_show_logs

        # Reboot
        tui_init 0 "Reboot now?"
        if (whiptail --yesno "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH"); then
            reboot
        fi
        exit 0
    fi

    # Error message
    tui_init 0 "ERROR: INSTALLATION FAILED!"
    whiptail --msgbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH"

    # Logs
    tui_show_logs

    exit 1
}

#/////////////////////////////////////////////////////
# INSTALL CORE
#/////////////////////////////////////////////////////

exec_install_core() {

    local uefi_mode="$1"
    local password_encryption="$2"
    local progress_result_file="$3"

    #----------------------------------------
    # Source config
    #----------------------------------------
    . "$INSTALLER_CONFIG_FILE"

    core_log "!!! INSTALLATION START !!!"
    if [ "$password_encryption" = "" ]; then core_log e "ERROR: Encryption Password is missing" && exit 1; fi
    core_log "Encryption Password is set!"

    #----------------------------------------
    # Wipe disk
    #----------------------------------------
    gauge_tui_update 4 "Wipe $DISK"
    # Destroy GPT and MBR data structures
    exec_command_wrap sgdisk -Z "$DISK"
    # Override complete disk with 0
    if [ "$WIPE_DISK" = "true" ]; then
        gauge_tui_update 6 "Wipe $DISK and override with zero (this will take a while...)"
        exec_command_wrap dd status=progress if=/dev/zero of="$DISK"
    fi

    #----------------------------------------
    # Partition disk
    #----------------------------------------
    gauge_tui_update 8 "Partition $DISK"

    # Create new partition table
    exec_command_wrap sgdisk -o "$DISK"

    # Reload partition table
    exec_command_wrap partprobe "$DISK"

    if [ "$uefi_mode" = "true" ]; then

        # /boot partition: 512MiB
        exec_command_wrap sgdisk -n 0:0:+512MiB -t 0:ef00 -c 0:boot "$DISK"

        # / partition: Rest of space
        exec_command_wrap sgdisk -n 0:0:0 -t 0:8300 -c 1:root "$DISK"

    else

        # BIOS only: 1MiB partition is needed for GRUB (if GPT is used instead of MBR)
        exec_command_wrap sgdisk -n 0:0:+1MiB -t 0:ef02 -c 0:grub "$DISK"

        # /boot partition: 512MiB
        exec_command_wrap sgdisk -n 0:0:+512MiB -t 0:8300 -c 0:boot "$DISK"

        # / partition: Rest of space
        exec_command_wrap sgdisk -n 0:0:0 -t 0:8300 -c 0:root "$DISK"
    fi

    #----------------------------------------
    # Encrypt disk
    #----------------------------------------
    gauge_tui_update 10 "Encrypt $DISK"

    # Create encryption
    # GRUB < 2.06: luks2 is not implemented!
    # local crypt_cmd="cryptsetup -c aes-xts-plain -s 512 luksFormat --type luks1 $ROOT_PARTITION"
    # Set encrypt command
    local crypt_cmd="cryptsetup -c aes-xts-plain -s 512 luksFormat $ROOT_PARTITION"

    # !! DO NOT USE exec_command_wrap
    if ! echo -n "$password_encryption" | $crypt_cmd -d - >/dev/null; then
        core_log "e" "$crypt_cmd"
        exit 1
    else
        core_log "c" "$crypt_cmd"
    fi

    # Open encrypt
    crypt_cmd="cryptsetup open $ROOT_PARTITION lvm"
    # !! DO NOT USE exec_command_wrap
    if ! echo -n "$password_encryption" | $crypt_cmd -d - >/dev/null; then
        core_log "e" "$crypt_cmd"
        exit 1
    else
        core_log "c" "$crypt_cmd"
    fi

    #----------------------------------------
    # LVM
    #----------------------------------------
    gauge_tui_update 10 "Create LVM ($DISK)"
    exec_command_wrap pvcreate /dev/mapper/lvm
    exec_command_wrap vgcreate main /dev/mapper/lvm
    exec_command_wrap lvcreate -l 100%FREE -n root main

    #----------------------------------------
    # Format disk
    #----------------------------------------
    gauge_tui_update 12 "Format $DISK"

    # Format /boot
    if [ "$uefi_mode" = "true" ]; then exec_command_wrap mkfs.fat -F 32 -n boot "$BOOT_PARTITION"; fi
    if [ "$uefi_mode" = "false" ]; then exec_command_wrap mkfs.ext4 -L boot "$BOOT_PARTITION"; fi

    # Format / (crypted)
    exec_command_wrap mkfs.ext4 -L root /dev/mapper/main-root

    #----------------------------------------
    # Mount disk to /mnt
    #----------------------------------------
    exec_command_wrap mount /dev/mapper/main-root /mnt
    exec_command_wrap mkdir /mnt/boot
    exec_command_wrap mount "$BOOT_PARTITION" /mnt/boot

    #----------------------------------------
    # Pacstrap base arch packages
    #----------------------------------------
    gauge_tui_update 24 "Pacstrap Installation (this will take a while)..."
    exec_command_wrap pacstrap /mnt base base-devel linux linux-firmware

    #----------------------------------------
    # Generate /etc/fstab
    #----------------------------------------
    gauge_tui_update 52 "Generate /etc/fstab"
    local log_txt="genfstab -Lp /mnt >>/mnt/etc/fstab"
    # genfstab -U
    if ! genfstab -Lp /mnt >>/mnt/etc/fstab; then
        core_log "e" "$log_txt"
        exit 1
    else
        core_log "c" "$log_txt"
    fi

    #----------------------------------------
    # Copy ecos installer in chroot env
    #----------------------------------------
    exec_command_wrap cp -f "$INSTALLER_SCRIPT_FILE" /mnt/$INSTALLER_ID
    exec_command_wrap cp -f "$INSTALLER_CONFIG_FILE" /mnt/$INSTALLER_ID.conf
    exec_command_wrap chmod +x /mnt/$INSTALLER_ID

    #----------------------------------------
    # Chroot into new system
    #----------------------------------------
    gauge_tui_update 54 "Enter CHROOT Environement"
    log_txt="arch-chroot /mnt /$INSTALLER_ID --chroot $uefi_mode <ENCRYPTION_PASSWORD>"
    if ! arch-chroot /mnt "/$INSTALLER_ID" --chroot "$uefi_mode" "$password_encryption"; then
        # FAILED
        core_log "e" "$log_txt"
        cleanup
        exit 1
    else
        # SUCCESS
        core_log "c" "$log_txt"
        cleanup
        gauge_tui_update 100 "Installation finished!"
        core_log "!!! INSTALLATION SUCCESSFULLY FINISHED !!!"
        # SET STATUS SUCCESS
        echo "PROGRESS_SUCCESS" >"$progress_result_file"
        exit 0
    fi
}

cleanup() {

    #----------------------------------------
    # Merge ecos logs
    #----------------------------------------
    wait && cat "/mnt/$INSTALLER_ID.log" >>"$INSTALLER_LOG_FILE"
    wait && cat "/mnt/$INSTALLER_ID.error" >>"$INSTALLER_LOG_FILE"
    rm -f "/mnt/$INSTALLER_ID"
    rm -f "/mnt/$INSTALLER_ID.conf"
    rm -f "/mnt/$INSTALLER_ID.log"
    rm -f "/mnt/$INSTALLER_ID.tui"
    rm -f "/mnt/$INSTALLER_ID.progress"

    #----------------------------------------
    # Unmount
    #----------------------------------------
    if [ "$AUTO_UNMOUNT" = "true" ]; then
        exec_command_wrap swapoff -a
        exec_command_wrap umount -R /mnt
    fi

}

#/////////////////////////////////////////////////////
# INSTALL CHROOT
#/////////////////////////////////////////////////////

exec_install_chroot() {

    local uefi_mode="$1"
    local password_encryption="$2"

    #----------------------------------------
    # Source config
    #----------------------------------------
    . "$INSTALLER_CONFIG_FILE"

    #----------------------------------------
    # Essential packages
    #----------------------------------------
    local gauge_txt="Install Essential Packages (this will take a while)..."

    gauge_tui_update 56 "$gauge_txt"
    exec_command_wrap pacman -Syy

    # Boootloader, Microcode Kernel Updates for CPU & Core Tools
    # os-prober will detect existings operating systems like Windows or other Linux Distributions
    gauge_tui_update 58 "$gauge_txt"
    local bootloader_pkgs="os-prober"
    [ "$uefi_mode" = "true" ] && bootloader_pkgs="$bootloader_pkgs efibootmgr"
    [ "$BOOTLOADER" = "grub" ] || [ "$uefi_mode" = "false" ] && bootloader_pkgs="$bootloader_pkgs grub"

    local ucode_pkg="$UCODE"
    [ "$ucode_pkg" = "disabled" ] && ucode_pkg=""
    exec_command_wrap pacman --noconfirm --needed -S $ucode_pkg $bootloader_pkgs dosfstools gptfdisk lvm2 $CUSTOM_PACKAGES

    # Network manager
    gauge_tui_update 60 "$gauge_txt"
    exec_command_wrap pacman --noconfirm --needed -S networkmanager

    # Git
    gauge_tui_update 64 "$gauge_txt"
    exec_command_wrap pacman --noconfirm --needed -S git

    # Nano
    gauge_tui_update 67 "$gauge_txt"
    exec_command_wrap pacman --noconfirm --needed -S nano

    # Default shell
    gauge_tui_update 72 "$gauge_txt"
    exec_command_wrap pacman --noconfirm --needed -S zsh

    # TLP DISABLED
    # if [ "$WORKSTATION" = "notebook" ]; then
    #     # Battery safer
    #     exec_command_wrap pacman --noconfirm --needed -S tlp
    # fi

    #----------------------------------------
    # Swap
    #----------------------------------------
    if [ "$SWAP_SIZE" != "0" ] && [ -n "$SWAP_SIZE" ]; then
        gauge_tui_update 75 "Create Swap File"
        exec_command_wrap dd if=/dev/zero of=/swapfile bs=1GiB count="$SWAP_SIZE" status=progress
        exec_command_wrap chmod 600 /swapfile
        exec_command_wrap mkswap /swapfile
        exec_command_wrap swapon /swapfile
        echo "# Swapfile" >>/etc/fstab
        echo "/swapfile none swap defaults 0 0" >>/etc/fstab
    fi

    #----------------------------------------
    # Timezone and localization
    #----------------------------------------
    exec_command_wrap ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
    exec_command_wrap hwclock --systohc

    #----------------------------------------
    # Keymap
    #----------------------------------------
    core_log "Create /etc/vconsole.conf"
    echo "KEYMAP=$VCONSOLE_KEYMAP" >/etc/vconsole.conf
    echo "FONT=lat9w-16" >>/etc/vconsole.conf

    #----------------------------------------
    # Locale
    #----------------------------------------
    core_log "Create /etc/locale.conf"
    echo "LANG=$LOCALE_LANG" >/etc/locale.conf

    #----------------------------------------
    # Set locale.gen
    #----------------------------------------
    for ((i = 0; i < ${#LOCALE_GEN[@]}; i++)); do
        local locale_gen_item="${LOCALE_GEN[$i]}"
        sed -i "s/^#$locale_gen_item/$locale_gen_item/g" "/etc/locale.gen"
    done
    gauge_tui_update 78 "Generate Locale"
    exec_command_wrap locale-gen

    #----------------------------------------
    # Set hostname
    #----------------------------------------
    core_log "Create /etc/hostname"
    echo "$HOSTNAME" >/etc/hostname

    #----------------------------------------
    # Set hosts
    #----------------------------------------
    core_log "Create /etc/hosts"
    {
        echo '127.0.0.1    localhost'
        echo '::1          localhost'
    } >/etc/hosts

    #----------------------------------------
    # Network
    #----------------------------------------
    gauge_tui_update 80 "Configure Network"
    exec_command_wrap systemctl enable NetworkManager

    #----------------------------------------
    # Modify HOOKS
    #----------------------------------------
    core_log "Modify /etc/mkinitcpio.conf"
    sed -i "s/MODULES=()/MODULES=(ext4)/g" /etc/mkinitcpio.conf
    sed -i "s/filesystems keyboard fsck/filesystems fsck/g" /etc/mkinitcpio.conf
    sed -i "s/udev autodetect/udev keyboard autodetect/g" /etc/mkinitcpio.conf
    sed -i "s/block filesystems fsck/block keymap encrypt filesystems fsck/g" /etc/mkinitcpio.conf
    sed -i "s/encrypt filesystems fsck/encrypt lvm2 filesystems fsck shutdown/g" /etc/mkinitcpio.conf

    #----------------------------------------
    # Rebuild initrc
    #----------------------------------------
    gauge_tui_update 82 "Rebuild Initial Ramdisk"
    exec_command_wrap mkinitcpio -P

    #----------------------------------------
    # Bootloader: systemd-boot (UEFI)
    #----------------------------------------
    gauge_tui_update 85 "Install Bootloader"

    if [ "$BOOTLOADER" = "systemd" ] && [ "$uefi_mode" = "true" ]; then

        # Install boot loeader
        exec_command_wrap bootctl --path=/boot install

        # Create bootloader config
        echo 'default ecos.conf' >/boot/loader/loader.conf
        echo 'console-mode auto' >>/boot/loader/loader.conf
        echo 'timeout 0' >>/boot/loader/loader.conf
        echo 'editor  yes' >>/boot/loader/loader.conf

        # Create arch default entry
        echo 'title   ECOS' >/boot/loader/entries/ecos.conf
        echo 'linux   /vmlinuz-linux' >>/boot/loader/entries/ecos.conf
        [ "$UCODE" != "disabled" ] && echo "initrd  /$UCODE.img" >>/boot/loader/entries/ecos.conf
        echo 'initrd  /initramfs-linux.img' >>/boot/loader/entries/ecos.conf
        echo "options cryptdevice=$ROOT_PARTITION:main root=/dev/mapper/main-root init=/usr/lib/systemd/systemd quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_priority=3 vt.global_cursor_default=0 rw" >>/boot/loader/entries/ecos.conf

        # Create arch fallback entry
        echo 'title   ECOS Fallback' >/boot/loader/entries/ecos-fallback.conf
        echo 'linux   /vmlinuz-linux' >>/boot/loader/entries/ecos-fallback.conf
        [ "$UCODE" != "disabled" ] && echo "initrd  /$UCODE.img" >>/boot/loader/entries/ecos-fallback.conf
        echo 'initrd  /initramfs-linux-fallback.img' >>/boot/loader/entries/ecos-fallback.conf
        echo "options cryptdevice=$ROOT_PARTITION:main root=/dev/mapper/main-root init=/usr/lib/systemd/systemd rw" >>/boot/loader/entries/ecos-fallback.conf
    fi

    #----------------------------------------
    # Bootloader: GRUB ( UEFI legacy BIOS support)
    #----------------------------------------

    if [ "$BOOTLOADER" = "grub" ] || [ "$uefi_mode" = "false" ]; then

        # Load EFI Variables
        if [ "$uefi_mode" = "true" ]; then
            mount -t efivarfs efivarfs /sys/firmware/efi/efivars
        fi

        # Install GRUB
        if [ "$uefi_mode" = "true" ]; then
            exec_command_wrap grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="ECOS" --recheck
        else
            exec_command_wrap grub-install --no-floppy "$BOOT_PARTITION" --recheck
        fi

        # GRUB Config (not needed)
        echo 'GRUB_CMDLINE_LINUX="cryptdevice='$ROOT_PARTITION':main root=/dev/mapper/main-root '$BOOT_ARGS'"' >/etc/default/grub
        echo 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"' >>/etc/default/grub
        echo 'GRUB_DISABLE_OS_PROBER="false"' >>/etc/default/grub
        echo 'GRUB_DISABLE_RECOVERY="false"' >>/etc/default/grub
        echo 'GRUB_DISABLE_LINUX_UUID="false"' >>/etc/default/grub
        [ "$uefi_mode" = "false" ] && echo 'GRUB_PRELOAD_MODULES="lvm"' >>/etc/default/grub
        echo 'GRUB_DISABLE_LINUX_UUID="false"' >>/etc/default/grub
        echo 'GRUB_TIMEOUT="2"' >>/etc/default/grub
        # exec_command_wrap grub-mkconfig -o /boot/grub/grub.cfg

        local ucode_line=""
        [ "$UCODE" != "disabled" ] && ucode_line="initrd	/intel-ucode.img /initramfs-linux.img\n"

        local grub_root=""
        [ "$uefi_mode" = "true" ] && grub_root="hd1,gpt1"
        [ "$uefi_mode" = "false" ] && grub_root="hd0,3"
        {
            echo -e "insmod all_video"
            echo -e "insmod gzio"
            echo -e "insmod part_gpt"
            echo -e "insmod fat"
            echo -e "set timeout=2"
            echo -e "set default=0"
            echo -e 'menuentry "ECOS" {'
            echo -e '	set root="'$grub_root'"'
            echo -e '	gfxpayload='$BOOTLOADER_RESOLUTION''
            echo -e '	linux	/vmlinuz-linux root=/dev/mapper/main-root rw cryptdevice='$ROOT_PARTITION':main root=/dev/mapper/main-root '$BOOT_ARGS' quiet'
            echo -e '	'$ucode_line'}'
        } >/boot/grub/grub.cfg
    fi

    #----------------------------------------
    # Create new user
    #----------------------------------------
    exec_command_wrap useradd -m -G users,wheel,video,audio,games,power,storage,disk -s /bin/zsh "$USERNAME"

    #----------------------------------------
    # Allow users in group wheel to use sudo
    #----------------------------------------
    core_log "Enable sudo in /etc/sudoers"
    sed -i '/%wheel\sALL=(ALL)\sALL/s/^#\s//g' /etc/sudoers

    #----------------------------------------
    # Auto login tty1
    #----------------------------------------
    gauge_tui_update 90 "Enable Automatic Login"
    mkdir -p "/etc/systemd/system/getty@tty1.service.d/"
    {
        echo "[Service]"
        echo "ExecStart="
        echo "ExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin $USERNAME --noclear %I \$TERM"
    } >"/etc/systemd/system/getty@tty1.service.d/override.conf"
    exec_command_wrap systemctl enable getty@tty1

    #----------------------------------------
    # Xorg config
    #----------------------------------------

    # Create dir
    exec_command_wrap mkdir -p /etc/X11/xorg.conf.d/

    #----------------------------------------
    # Keyboard config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/00-keyboard.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "keyboard"'
        echo '    MatchIsKeyboard "yes"'
        echo '    Option "XkbLayout" "'$X11_KEYBOARD_LAYOUT'"'
        echo '    Option "XkbModel" "pc105"'
        echo '    Option "XkbVariant" "'$X11_KEYBOARD_VARIANT'"'
        echo 'EndSection'
    } >"/etc/X11/xorg.conf.d/00-keyboard.conf"

    #----------------------------------------
    # Mouse config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/50-mouse.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "mouse"'
        echo '    Driver "libinput"'
        echo '    MatchIsPointer "yes"'
        echo '    Option "AccelProfile" "flat"'
        echo '    Option "AccelSpeed" "0"'
        echo 'EndSection'
    } >"/etc/X11/xorg.conf.d/50-mouse.conf"

    #----------------------------------------
    # Touchpad config
    #----------------------------------------
    core_log "Create /etc/X11/xorg.conf.d/70-touchpad.conf"
    {
        echo 'Section "InputClass"'
        echo '    Identifier "touchpad"'
        echo '    Driver "libinput"'
        echo '    MatchIsTouchpad "on"'
        echo '    Option "ClickMethod" "clickfinger"'
        echo '    Option "Tapping" "off"'
        echo '    Option "NaturalScrolling" "true"'
        echo 'EndSection'

    } >"/etc/X11/xorg.conf.d/70-touchpad.conf"

    gauge_tui_update 90 "Enable Daemons"

    #----------------------------------------
    # SSD fstrim
    #----------------------------------------
    exec_command_wrap systemctl enable "fstrim.timer"

    #----------------------------------------
    # Timesync service
    #----------------------------------------
    exec_command_wrap systemctl enable "systemd-timesyncd.service"

    #----------------------------------------
    # TODO (FAILED): Network browsing service
    #----------------------------------------
    #exec_command_wrap systemctl enable "avahi-daemon"

    #----------------------------------------
    # TLP (Notebook)
    #----------------------------------------
    # if [ "$WORKSTATION" = "notebook" ]; then
    #     exec_command_wrap systemctl enable "tlp.service"
    # fi

    #----------------------------------------
    # Pacman colors & multilib
    #----------------------------------------
    gauge_tui_update 90 "Configure Pacman"
    core_log "Enable pacman multilib & colors"
    sed -i 's/^#Color/Color/g;/#\[multilib\]/,/#Include/ s/^#//g' /etc/pacman.conf
    exec_command_wrap pacman -Syy

    #----------------------------------------
    # ECOS Repo
    #----------------------------------------
    gauge_tui_update 92 "Initilize ECOS"
    core_log "Initilize ECOS in ~/.ecos"
    local ecos_system_dir="/home/$USERNAME/.ecos/.system"
    local ecos_repo_dir="$ecos_system_dir/repo"
    exec_command_wrap mkdir -p "$ecos_system_dir"
    exec_command_wrap /usr/bin/git clone "$ECOS_REPO_URL" "$ecos_repo_dir"
    exec_command_wrap chmod +x "$ecos_repo_dir/ecos"
    exec_command_wrap chmod +x "$ecos_repo_dir/installer"

    # Create .zlogin
    core_log "Creating ~/.zlogin"
    local user_profile="/home/$USERNAME/.zlogin"
    echo '#!/bin/sh' >$user_profile
    echo 'export ECOS_HOME="$HOME/.ecos"' >>$user_profile
    echo 'export PATH="$PATH:$ECOS_HOME/.system/repo/"' >>$user_profile
    echo 'export ECOS_CORE="$ECOS_HOME/.system/repo/ecos"' >>$user_profile
    echo '$ECOS_CORE --install' >>$user_profile
    exec_command_wrap chmod +x $user_profile

    #----------------------------------------
    # Deletes unnecessary files
    #----------------------------------------
    core_log "Deletes unnecessary files"
    exec_command_wrap rm -f "/home/$USERNAME/.bash_logout"
    exec_command_wrap rm -f "/home/$USERNAME/.bash_profile"
    exec_command_wrap rm -f "/home/$USERNAME/.bashrc"
    exec_command_wrap rm -f "/home/$USERNAME/.zshrc"

    #----------------------------------------
    # Set correct user permissions
    #----------------------------------------
    core_log "Set correct user permissions"
    exec_command_wrap chown -R "$USERNAME":"$USERNAME" "/home/$USERNAME"

    #----------------------------------------
    # Change passwords
    #----------------------------------------
    gauge_tui_update 98 "Change Passwords (flickering message is ok)"
    core_log "Change passwords"
    sleep 1
    # passwd root < <(echo -e "$password_encryption\n$password_encryption")
    # passwd "$USERNAME" < <(echo -e "$password_encryption\n$password_encryption")
    clear && wait && echo -e "${ECOS_DEFAULT_PASSWORD}\n${ECOS_DEFAULT_PASSWORD}" | (passwd)
    clear && wait && echo -e "${ECOS_DEFAULT_PASSWORD}\n${ECOS_DEFAULT_PASSWORD}" | (passwd "$USERNAME")

    #----------------------------------------
    # Chroot finished
    #----------------------------------------
    core_log "CHROOT successfully finished"
}

#/////////////////////////////////////////////////////
# CHECK CONFIGURATION
#/////////////////////////////////////////////////////

check_config() {

    if [ -f "$INSTALLER_CONFIG_FILE" ]; then
        . "$INSTALLER_CONFIG_FILE"
    fi

    #----------------------------------------
    # Check user
    #----------------------------------------
    if [ "$USERNAME" = "" ]; then
        tui_init 0 "Enter Username"
        if ! USERNAME=$(whiptail --inputbox "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH" 3>&1 1>&2 2>&3); then
            tui_core_installer_menu
            exit 0
        fi
        if [ "$USERNAME" = "" ]; then
            tui_init 0 "Username was empty! Restart the Installation..."
            whiptail --textbox "$TUI_FILE" "$TUI_HEIGHT" "$TUI_WIDTH"
            tui_core_installer_menu
            exit 0
        fi
        replace_property_value "$INSTALLER_CONFIG_FILE" "USERNAME" "$USERNAME"
    fi

    #----------------------------------------
    # Check workstation
    #----------------------------------------
    if [ "$WORKSTATION" = "" ]; then
        tui_init 20 "Choose Workstation"
        if ! WORKSTATION=$(whiptail --menu --notags "$(cat "$TUI_FILE")\n" "$TUI_HEIGHT" "$TUI_WIDTH" 2 "desktop" "Desktop" "notebook" "Notebook" 3>&1 1>&2 2>&3); then
            tui_core_installer_menu
            exit 0
        fi
        replace_property_value "$INSTALLER_CONFIG_FILE" "HOSTNAME" "$USERNAME-$WORKSTATION"
        replace_property_value "$INSTALLER_CONFIG_FILE" "WORKSTATION" "$WORKSTATION"
    fi

    #----------------------------------------
    # Check Language
    #----------------------------------------
    if [ "$LOCALE_LANG" = "" ] || [ ${#LOCALE_GEN[@]} = 0 ] || [ "$TIMEZONE" = "" ] || [ "$VCONSOLE_KEYMAP" = "" ] || [ "$X11_KEYBOARD_LAYOUT" = "" ] || [ "$X11_KEYBOARD_VARIANT" = "" ]; then

        tui_init 19 "Choose Setup Language"
        if ! lang_result=$(whiptail --menu --notags "$(cat "$TUI_FILE")\n" "$TUI_HEIGHT" "$TUI_WIDTH" 2 "en_US" "English" "de_DE" "German" 3>&1 1>&2 2>&3); then
            tui_core_installer_menu
            exit 0
        fi
        if [ "$lang_result" = "en_US" ]; then
            set_lang_en_US
        fi

        if [ "$lang_result" = "de_DE" ]; then
            set_lang_de_DE
        fi

        replace_property_value "$INSTALLER_CONFIG_FILE" "TIMEZONE" "$TIMEZONE"
        replace_property_value "$INSTALLER_CONFIG_FILE" "LOCALE_LANG" "$LOCALE_LANG"
        replace_property_array_value "$INSTALLER_CONFIG_FILE" "LOCALE_GEN" "${LOCALE_GEN[@]}"
        replace_property_value "$INSTALLER_CONFIG_FILE" "VCONSOLE_KEYMAP" "$VCONSOLE_KEYMAP"
        replace_property_value "$INSTALLER_CONFIG_FILE" "X11_KEYBOARD_LAYOUT" "$X11_KEYBOARD_LAYOUT"
        replace_property_value "$INSTALLER_CONFIG_FILE" "X11_KEYBOARD_VARIANT" "$X11_KEYBOARD_VARIANT"
    fi

    #----------------------------------------
    # Check Microcode
    #----------------------------------------
    if [ "$UCODE" = "" ]; then
        tui_init 17 "Choose Processor Microcode"
        if ! UCODE=$(whiptail --menu --notags "$(cat "$TUI_FILE")\n" "$TUI_HEIGHT" "$TUI_WIDTH" 3 "disabled" "Disable" "intel-ucode" "Intel" "amd-ucode" "AMD" 3>&1 1>&2 2>&3); then
            tui_core_installer_menu
            exit 0
        fi
        replace_property_value "$INSTALLER_CONFIG_FILE" "UCODE" "$UCODE"
    fi

    #----------------------------------------
    # Check disk
    #----------------------------------------
    check_config_disk
    replace_property_value "$INSTALLER_CONFIG_FILE" "DISK" "$DISK"
    replace_property_value "$INSTALLER_CONFIG_FILE" "BOOT_PARTITION" "$BOOT_PARTITION"
    replace_property_value "$INSTALLER_CONFIG_FILE" "ROOT_PARTITION" "$ROOT_PARTITION"

    #----------------------------------------
    # Add default values
    #----------------------------------------
    check_config_key "$INSTALLER_CONFIG_FILE" "BOOTLOADER" "$BOOTLOADER"
    check_config_key "$INSTALLER_CONFIG_FILE" "BOOTLOADER_RESOLUTION" "$BOOTLOADER_RESOLUTION"
    check_config_key "$INSTALLER_CONFIG_FILE" "BOOT_ARGS" "$BOOT_ARGS"
    check_config_key "$INSTALLER_CONFIG_FILE" "DUALBOOT" "$DUALBOOT"
    check_config_key "$INSTALLER_CONFIG_FILE" "WIPE_DISK" "$WIPE_DISK"
    check_config_key "$INSTALLER_CONFIG_FILE" "SWAP_SIZE" "$SWAP_SIZE"
    check_config_key "$INSTALLER_CONFIG_FILE" "AUTO_UNMOUNT" "$AUTO_UNMOUNT"
    check_config_key "$INSTALLER_CONFIG_FILE" "CUSTOM_PACKAGES" "$CUSTOM_PACKAGES"

    #----------------------------------------
    # Show default config screen
    #----------------------------------------
    tui_init 0 "$(cat "$INSTALLER_CONFIG_FILE")"
    tui_add 28 "\nEdit Setup Configuration?"
    local line="#############################################################"
    local setup_cfg="$line\nSETUP CONFIGURATION\n$line\n\n$(cat "$INSTALLER_CONFIG_FILE")\n\n$line\n\nEdit Configuration?"
    if (whiptail "$setup_cfg" --yesno 0 0); then
        nano "$INSTALLER_CONFIG_FILE"
        wait
        # Check again after edit
        check_config
    fi

    #----------------------------------------
    # Source changes
    #----------------------------------------
    . "$INSTALLER_CONFIG_FILE"
}

check_config_disk() {

    if [ "$1" = "--force" ] || [ "$DISK" = "" ] || [ "$BOOT_PARTITION" = "" ] || [ "$ROOT_PARTITION" = "" ]; then

        local disk_array=()
        while read disk_line; do
            local disk_size=$(lsblk -d -n -o SIZE /dev/$disk_line)
            disk_array+=("/dev/$disk_line")
            disk_array+=(" ($disk_size)")
        done < <(lsblk -I 8,259,254 -d -o KNAME -n)

        if [ ${#disk_array[@]} == 0 ]; then
            tui_init 0 "No supported Disk found"
            whiptail --msgbox "$(cat "$TUI_FILE")" 0 "$TUI_WIDTH"
            exit 1
        fi

        tui_init 24 "Choose Disk"
        if ! DISK=$(whiptail --menu "$(cat "$TUI_FILE")" "$TUI_HEIGHT" "$TUI_WIDTH" "${#disk_array[@]}" "${disk_array[@]}" 3>&1 1>&2 2>&3); then
            tui_core_installer_menu
            exit 0
        fi

        BOOT_PARTITION="${DISK}1"
        ROOT_PARTITION="${DISK}2"

        # NVM Express
        if [[ "$DISK" = "/dev/nvm"* ]]; then
            BOOT_PARTITION="${DISK}p1"
            ROOT_PARTITION="${DISK}p2"
        fi
    fi
}

#/////////////////////////////////////////////////////
# RECOVERY
#/////////////////////////////////////////////////////

tui_open_recovery() {

    local uefi_mode="$1"

    #----------------------------------------
    # Select Disk
    #----------------------------------------
    check_config_disk --force

    #----------------------------------------
    # Open Crypt
    #----------------------------------------
    clear
    print_info "OPEN CRYPTED DEVICE" "$ROOT_PARTITION"
    echo -e "\nENTER YOUR ENCRYPTION PASSWORD\n"
    cryptsetup open $ROOT_PARTITION lvm

    #----------------------------------------
    # Mount
    #----------------------------------------
    local mnt_recovery='/mnt/recovery'
    print_info "MOUNT TO" "$mnt_recovery"
    mkdir -p "$mnt_recovery"
    mount /dev/mapper/main-root "$mnt_recovery"
    mkdir -p "$mnt_recovery/boot"
    mount -p "$BOOT_PARTITION" "$mnt_recovery/boot"

    #----------------------------------------
    # Chroot
    #----------------------------------------
    clear
    print_info "CHROOT" "$mnt_recovery"

    # Mount /boot in recovery system (UEFI only)
    if [ "$uefi_mode" = "true" ]; then
        if ! arch-chroot "$mnt_recovery" mount $BOOT_PARTITION /boot; then
            echo "ERROR: CHROOT Mount /boot"
            exit 1
        fi
    fi
    echo -e "\n"
    echo -e "!! YOUR ARE NOW ON YOUR RECOVERY SYSTEM !!"
    echo -e "        Leave with command 'exit'         "
    echo -e "\n"
    arch-chroot "$mnt_recovery"
    wait

    #----------------------------------------
    # Unmount
    #----------------------------------------
    swapoff -a
    umount -R "$mnt_recovery"
    wait && clear
}

#/////////////////////////////////////////////////////
# CREATE BOOTABLE USB STICK
#/////////////////////////////////////////////////////

tui_create_usb() {

    clear

    if ! [ -x "$(command -v whiptail)" ]; then
        echo "ERROR: whiptail not installed"
        exit 1
    fi

    if ! [ -x "$(command -v curl)" ]; then
        echo "ERROR: curl not installed"
        exit 1
    fi

    if ! [ -x "$(command -v dd)" ]; then
        echo "ERROR: dd not installed"
        exit 1
    fi

    # Select Disk
    #--------------------------------------------
    local disk_array=()
    while read disk_line; do
        disk_size=$(lsblk -d -n -o SIZE /dev/$disk_line)
        disk_array+=("/dev/$disk_line")
        disk_array+=(" ($disk_size)")
    done < <(lsblk -I 8 -d -o KNAME -n)

    if [ ${#disk_array[@]} == 0 ]; then
        tui_init 0 "No supported Disk found"
        whiptail --msgbox "$(cat "$TUI_FILE")" 0 "$TUI_WIDTH"
        exit 1
    fi

    local usb_disk=''
    tui_init 17 "CREATE BOOTABLE USB STICK"
    tui_add 20 "Choose Target Device"
    if ! usb_disk=$(whiptail --menu "$(cat "$TUI_FILE")\n" "$TUI_HEIGHT" "$TUI_WIDTH" "${#disk_array[@]}" "${disk_array[@]}" 3>&1 1>&2 2>&3); then
        exit 0
    fi

    local local_iso_dir="/tmp/arch-iso"
    local iso_url="$ECOS_ARCH_ISO_ROOT_URL/$ECOS_ARCH_ISO_FILE"
    local sha1_url="$ECOS_ARCH_ISO_ROOT_URL/$ECOS_ARCH_ISO_SHA1"
    local local_iso_file="$local_iso_dir/$ECOS_ARCH_ISO_FILE"
    local local_sha1_file="$local_iso_dir/$ECOS_ARCH_ISO_FILE.sha1"

    mkdir -p "$local_iso_dir"

    # Check and download arch iso
    #--------------------------------------------
    print_info "Target USB Device" "$usb_disk"

    # Downloading ISO
    if ! [ -f "$local_iso_file" ]; then
        print_info "Downloading Arch ISO" "$iso_url"
        if ! curl -L "$iso_url" -o "$local_iso_file.part"; then
            echo "ERROR: Downloading ISO $iso_url"
            exit 1
        fi
        wait
        if ! mv "$local_iso_file.part" "$local_iso_file"; then
            echo "ERROR: Moving ISO $local_iso_file"
            exit 1
        fi
    fi

    # Downloading SHA1 Sum
    if ! [ -f "$local_sha1_file" ]; then
        print_info "Downloading SHA1 Checksum" "$sha1_url"
        if ! curl -L "$sha1_url" -o "$local_sha1_file.part"; then
            echo "ERROR: Downloading SHA1 Sum $sha1_url"
            exit 1
        fi
        wait
        if ! mv "$local_sha1_file.part" "$local_sha1_file"; then
            echo "ERROR: Moving SHA1 Sum $local_sha1_file"
            exit 1
        fi
    fi

    # Check SHA1 Sum
    cd "$local_iso_dir" || exit 1
    if grep -qrnw "$local_sha1_file" -e "$(sha1sum "$ECOS_ARCH_ISO_FILE")"; then
        print_info "SHA1 Checksum" "correct"
    else
        echo "ERROR: SHA1 Checksum" "incorrect"
        exit 1
    fi

    print_info "Arch ISO File" "$local_iso_file"

    # Create Bootable USB Stick
    #--------------------------------------------
    print_info "Create Bootable USB Device..."

    if ! sudo dd bs=4M if="$local_iso_file" of="$usb_disk" status=progress oflag=sync; then
        echo "ERROR: Creating USB Stick"
        exit 1
    fi

    # Finished
    wait && print_info "FINISHED" "Please remove the USB Device $usb_disk"
}

#/////////////////////////////////////////////////////
# LOGGING
#/////////////////////////////////////////////////////

core_log() {

    touch "$INSTALLER_LOG_FILE"

    # Default vaules
    local lvl="INFO"
    local text="$1"

    # Handle if 2. parameter is set
    if [ "$2" != "" ]; then

        if [ "$1" = "c" ]; then
            lvl="EXEC"
        fi

        if [ "$1" = "e" ]; then
            lvl="FAIL"
        fi

        # Shift to 2. argument to you $* for all instead of $2
        shift
        text="$*"
    fi

    # Style log output
    local styled_text="$(date "+%Y-%m-%d %H:%M:%S") $INSTALLER_ID | $lvl | $text"

    # Print to STOUT & INSTALLER_LOG_FILE
    printf '%s\n' "$styled_text" >>"$INSTALLER_LOG_FILE"
    printf '%s\n' "$styled_text"
}

tui_show_logs() {
    touch "$INSTALLER_LOG_FILE"
    tui_init 0 "$(cat "$INSTALLER_LOG_FILE")"
    #whiptail --textbox $TUI_FILE 0 $TUI_WIDTH
    whiptail --msgbox "$(cat "$TUI_FILE")" 0 "$TUI_WIDTH"
}

#/////////////////////////////////////////////////////
# HELPER FUNCTIONS
#/////////////////////////////////////////////////////

exec_command_wrap() {
    # !!! DO NOT USE WITH PIPE (|) OR REDIRECT (>>) !!!

    local command_txt="$*"
    local tmp_error="$INSTALLER_WORKING_DIR/$INSTALLER_ID.error"

    if "$@" >/dev/null 2>"$tmp_error"; then
        core_log "c" "$command_txt"
        rm -f "$tmp_error"
        return 0
    else
        core_log "e" "$command_txt"
        exit 1
    fi
}

gauge_tui_update() {
    local percent="$1"
    local text="$2"
    tui_init 0 "$text"
    echo -e "XXX\n$percent\n$(cat "$TUI_FILE")\nXXX"
}

check_config_key() {
    local config_file="$1"
    local config_key="$2"
    local default_value="$3"
    touch "$config_file"
    if ! grep -qrnw "$config_file" -e "$config_key=*"; then
        echo "$config_key=\"$default_value\"" >>"$config_file"
    fi
}

replace_property_value() {
    local config_file="$1"
    local config_key="$2"
    local config_value="$3"
    check_config_key "$config_file" "$config_key" ""
    sed -i "s;${config_key}=.*;${config_key}=\"${config_value}\";g" "$config_file"
}

replace_property_array_value() {

    local config_file="$1" && shift
    local config_key=$1 && shift
    local config_value_list=("$@")
    local new_value_item_list=""

    for ((i = 0; i < ${#config_value_list[@]}; i++)); do
        local array_item="${config_value_list[$i]}"

        # First item without leading space
        if [ $i = 0 ]; then
            new_value_item_list="\"$array_item\""
            continue
        fi

        # Other items
        new_value_item_list="$new_value_item_list \"$array_item\""
    done

    # Replace items (without "")
    check_config_key "$config_file" "$config_key" ""
    sed -i "s;${config_key}=.*;${config_key}=(${new_value_item_list});g" "$config_file"
}

tui_init() {
    rm -f "$TUI_FILE"
    local uefi_info="BIOS Mode"
    [ "$UEFI_ENABLED" = "true" ] && uefi_info="UEFI Mode"
    echo -e '
             ███████  ██████  ██████  ███████ 
             ██      ██      ██    ██ ██      
             █████   ██      ██    ██ ███████ 
             ██      ██      ██    ██      ██ 
             ███████  ██████  ██████  ███████\n
                       - '$uefi_info' -
             ' >"$TUI_FILE"
    tui_add "$1" "$2"
}

tui_add() {

    echo_whitespaces() {
        #----------------------------------------
        # Echo a string with leading spaces
        #   $1: number of spaces
        #   $2: string
        #----------------------------------------
        local spaces=""
        for i in $(seq 1 "$1"); do
            spaces=" ${spaces}"
        done
        echo -e "$spaces""$2"
    }

    echo -e "$(echo_whitespaces "$1" "$2")\n" >>"$TUI_FILE"

    # Wait for file is ready
    sleep 0.1
}

print_info() {
    local title="$1"
    local info="$2"
    local prefix="${TERM_COLOR_BLUE}>>>${TERM_COLOR_NULL}"
    local output="${prefix} ${TERM_COLOR_PURPLE}${title}${TERM_COLOR_NULL}"
    if [ "$info" != "" ]; then
        output="${output}: ${TERM_COLOR_YELLOW}${info}${TERM_COLOR_NULL}"
    fi
    echo -e "\n$output"
}

#/////////////////////////////////////////////////////
# TRAP
#/////////////////////////////////////////////////////

on_trap() {
    rm -f "$TUI_FILE"
    rm -f "$PROGRESS_FILE"
}

# Set trap
trap 'on_trap' 0 1 3 6

#/////////////////////////////////////////////////////
# START
#/////////////////////////////////////////////////////

main "$@"
